- src/components/mdc/_theme.scss
- Make primary variant color non-white (so TextField floating labels don't "disappear")
> Make primary variant color non-white

- src/pages/household/settings/dependent/[uuid].svelte
- Go back to household / settings after removing a dependent
> Go back to household / settings after removing a dependent

- src/pages/_layout.svelte
- src/pages/items/new.svelte
- Fix menu link to "New item" form
- Add back in the UI (dropdown) for a new item's category
- Remove "Risk category" from UI, since that will come from Category
- Rename "Item cost" to "Market value" on new-item form
- Switch new-item form's "Market value" field to use MoneyInput
> Update the new-item form

- src/components/AppHeader.svelte
- src/components/mdc/Menu/Menu.svelte
- src/pages/home.svelte
- bug requiring a second click to open menu
- bug causing an extra focusable mdc-list-item
Do we need the menu items to remain an anchor element? Seems to work fine with `<li>` but thought you and Levi mentioned something about needing it for the breadcrumbs.
> Menu bugfixes

- src/data/items.js
- src/pages/home.svelte
- src/pages/household/settings.svelte
- Only try to load the items if we have a policy ID
- Don't load the list of dependents until we have a policy ID
- Fix parameter documentation for `getItems()`
> Avoid API calls with a policy id of `null`

- src/components/Breadcrumb.svelte
- Make links prop optional on Breadcrumb, to match our usage
- Replace loose-comparison operator
> Breadcrumb cleanup

- src/data/policy-members.js
- src/pages/household/settings.svelte
- Load household members from API
- Cache policy members, but refresh on each visit to household settings
---
I'm curious what you think about this "caching" strategy, @Schparky and @hobbitronics. This avoids an empty list of household members after we've loaded them the first time, but ensures the user sees current data quickly even on subsequent visits to that page. (Note that this is only caching them in memory, not across full page reloads.)
> Household policy members

- src/data/dependents.js
- src/pages/household/settings.svelte
- src/pages/household/settings/dependent/[uuid].svelte
- Refactor dependents store to be grouped by policy ID
- Use API URL path as unique start/stop key for "dependent" data functions
- Remove unused import
- Update household settings page to use `$dependentsByPolicyId`
- Update edit-dependent page to use `$dependentsByPolicyId`
> Group dependents data by policy ID

- src/data/itemCategories.js
- src/data/items.js
- src/dates.js
- src/pages/items/new.svelte
- Parsed formdata to make the PolicyItemCreate api call. Example from console below
- brought in Dependants
- added dates/index.js for formatting dates
- refactored and added some mock data back in for non-hydrated api fields
```
category_id: "63bcf980-e1f0-42d3-b2b0-2e4704159f4f"
country: "USA"
coverage_amount: 123
coverage_start_date: "2021-08-17"
coverage_status: "Draft"
description: "iphone se"
in_storage: false
make: "se"
model: "iphone"
name: "se"
purchase_date: "2021-08-17"
serial_number: "123"
```
Note: still getting an error from the server:` debug_msg: "failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: insert or update on table \"items\" violates foreign key constraint …
> PolicyCreateItem api call

- src/pages/household/settings.svelte
- Display the list of household members and dependents as a single list
---
I noticed it's that way in the mockup.
> Display the list of household members and dependents as a single list

- src/components/ClaimCard.svelte
- src/components/ClaimCardBanner.svelte
- src/components/ClaimCards.svelte
- src/data/claims.js
- src/pages/claims.svelte
- src/pages/home.svelte
- src/pages/items/[itemId]/new-claim.svelte
- Extract ClaimCardBanner component (for banner at top of ClaimCard)
- Update getState() to use a claim's status (untested)
- Fix retrieval of items on new-claim page
- Update new-claim page's check for whether an item was found
- Pass the list of claims (not items) into the ClaimCards component
- Show a ClaimCard for each item on each claim, not just for each claim
- Change ClaimCard(s) to dispatch events rather than calling `$goto`, since they're just components
- Update "claims" page to listen for events and handle URL changes, since it's a page
---
We're waiting on some changes on the API (returning the list of items with the claim's data), so I haven't fully tested this, but it seems to build successfully and work as far as I can manually test.
> Adjust claims page

- src/components/ClaimCard.svelte
- src/components/dates.js
- src/data/index.js
- src/pages/claims/[claimId].svelte
Added a form to upload receipt and replacement cost for status of Needs_initial_changes and event_type of theft.
This will also likely be used for other replacement views, but we need information from the api to know if it is a replacement.
Since there isn't working endpoint to this yet it will need to be finished later
> added Needs_initial_changes Theft claim view

- src/pages/household/settings.svelte
Fixed:
- householdId field didn't fill with existing Id
- Leaving the field saved/updated even if no changes were made
- policies needed to be loaded on hard refresh
> load policies and only update when different

- src/pages/household/settings.svelte
Added:
- `<datalist>` for Affiliate organizaiton (like select but searchable)
- styling for the input
- function for updating policies.entity_code
- control block for the affiliatiton field
I will be putting the datalist element into a component next, but wanted to see if it served our purposes first.
> update affiliate organization

- src/data/claims.js
- src/pages/claims/[claimId]/edit.svelte
- Fix `updateClaim()` function to use "claimId", not "itemId"
---
I don't think this was in use (much) yet, but while it had my attention I went and and made the change.
> Fix `updateClaim()`

- src/components/FileDropArea/FileDropArea.svelte
- src/data/claims.js
- src/pages/claims/[claimId].svelte
- claimsFileAttach
- call claimsFileAttach from [ClaimsID]
- reset files after uploading
- remove preview from the FileDropArea after uploading
- show receipts on a claim
> update a claim with receipts

- src/components/FileDropArea/FileDropArea.svelte
- src/components/FileDropArea/_index.scss
- src/pages/claims/[claimId].svelte
- delete event
- preview id
- mimeTypes prop
- vanilla js to svelte each loop
- previews are now external to dropzone
- styling to match mockup
- only one Progress.Circular shown at a time
> FileDropArea refinement

- src/components/FileDropArea/FileDropArea.svelte
- src/components/FileDropArea/_index.scss
- src/components/FilePreview/FilePreview.svelte
- src/components/FilePreview/_index.scss
- src/components/FilePreview/index.js
- src/components/dates.js
- src/components/index.js
- src/pages/claims/[claimId].svelte
Talked with Alex and found out the previews are actully uploaded.
- upload receipt button
- each loop showing receipts
- onSubmit
- thumbnail from previews
- Upload now uploads and attaches files to claims
- moved previews into FilePreview component
- show one receipt at a time
- FilePreview component
- preview event to show one image
-  show created_at
> Previews are uploaded receipts

- src/components/ClaimCard.svelte
- src/components/ClaimCards.svelte
- src/data/claims.ts
- src/pages/claims.svelte
- src/pages/claims/[claimId].svelte
Alex told me ClaimCard action should be 'View claim' and the entire card non-clickable.
- editClaim, onKeyPress from ClaimCard
- actionLabel from states
- moved gotoClaim to claimCards.svelte since the action button wasn't working in /home
> ClaimCard action revision

- src/data/items.ts
- src/data/policies.ts
- src/pages/policies.svelte
- Add simple Policies page/table (mostly for administrative purposes)
- Remove duplicate `Policy` definition from items data file
- Move `PolicyType` from items to claims data file
> Add a policies page

- src/business-rules/claim-payout-amount.js
- src/business-rules/claim-payout-amount.ts
- src/components/FilePreview/FilePreview.svelte
- src/data/claims.ts
- src/pages/claims/[claimId].svelte
- filePurpose
- getFilePurpose()
- needsEvidence
- needsFile
- uploadLabel
- control block around FileDropArea and MoneyInput in [claimID]
- animation delay on FilePreview
- business-rules to use ts
- bug: wrong payout option 'replace'
Realized we need the second "needs changes" banner since we are requiring files.
> Draft uploads and file purpose

- src/business-rules/claim-payout-amount.ts
- src/components/forms/ClaimForm.svelte
- src/data/claim-event-types.ts
- src/data/claim-incident-types.ts
- src/data/claims.ts
- src/pages/claims/[claimId].svelte
- src/pages/policies/[policyId].svelte
- Change "claim event"-related names to "claim incident"-related names
- Remove completed TODO comment
- In "data/claims" file, rename `ClaimIncidentType` to `ClaimIncidentTypeName` to reflect that it's the name, not the full object, and avoid type-name conflict with `ClaimIncidentType` object structure
> Rename event to incident

- src/pages/claims/[claimId].svelte
- src/pages/claims/[claimId]/edit.svelte
There were some typos.
I thought about getting rid of the editClaim function and just giving the button the relative url. Any benefits to using $goto?
> fixed editClaim url

- src/components/AppHeader.svelte
- src/components/mdc/Menu/Menu.svelte
- src/pages/home.svelte
While reviewing the Menu ui-components PR I realized the syncToggler event isn't needed and doesn't fire.
> simplify Menu closing

- src/helpers/money.ts
- Return an empty string from `formatMoney()` if cents are NaN
> Return an empty string from `formatMoney()` if cents are NaN

- src/components/App.svelte
a change in error type introduced a regression in the authentication redirect code when a 401 is hit. better type data was added. ;)
mea culpa! mea culpa! I break it, I fix it.
> fix the auth redirect issue

- src/business-rules/claim-payout-amount.ts
- src/components/MoneyInput.svelte
- src/components/RadioOptions.svelte
- src/components/forms/ClaimForm.svelte
- src/data/claims.ts
- src/pages/claims/[claimId].svelte
- src/pages/claims/[claimId]/edit.svelte
* update save claim item to persist to store
* add more typings
* fix some typings
Some of the components rely on a bit of a "trinary" system where they manually set values to 'undefined'. this is a bit of a code smell to me but beyond the current scope.
> fix claim form to load money values

- src/data/claims.ts
- Use `updateClaimsStore()` in one more place in claims.ts
---
This is a follow-up on [this comment](https://github.com/silinternational/cover-ui/pull/155#pullrequestreview-763437478)
> Use `updateClaimsStore()` in one more place in claims.ts

- src/business-rules/claim-payout-amount.ts
- src/components/forms/ClaimForm.svelte
- src/pages/claims.svelte
- src/pages/claims/[claimId].svelte
- src/pages/claims/[claimId]/edit.svelte
- src/pages/items/[itemId]/new-claim.svelte
- Add "Save For Later" button to ClaimForm
- Actually submit the claim when "Submit Claim" is clicked while creating/editing
- Fix formatting of "We could not find that claim" message
- Extract `isEvidenceNeeded()` to business rules
- Allow user to provide evidence at `Review1` claim status, too
> "Save For Later" button for Claims

- src/components/App.svelte
- Ensure "Accountable Persons" list has entries, by re-retrieving the user data if it didn't come back with a policy_id
> Re-load the user data (after a delay) if we didn't get their policy_id

- src/components/home/UserHomePage.svelte
ClaimCards don't dispatch "edit-claim" events any more.
> Remove "goto edit-claim page" code from UserHomePage component

- src/business-rules/claim-payout-amount.ts
- src/components/banners/ClaimBanner.svelte
- src/pages/claims/[claimId].svelte
- src/pages/claims/[claimId]/edit.svelte
- ClaimBanner to /[claimID]/edit.svelte
- `$: claimStatus === 'Draft' && editClaim()` to [ClaimID].svelte
- `$$props.class` to ClaimBanner.svelte
- onSaveForLater to redirect to /home
- canProvideEvidenceNow to only include 'Review1'
> Claim of status: "Draft" redirects to /claimID/edit, "save for later" button redirects to /home

- src/components/banners/ItemBanner.svelte
- src/pages/items/[itemId].svelte
- src/pages/items/[itemId]/edit.svelte
- ItemBanner to /[itemID]/edit.svelte
- $: status === 'Draft' && goToEditItem() to [itemID].svelte
- $$props.class to ItemBanner.svelte
- onSaveForLater to redirect to /home
-
> "Draft" item view should redirect to edit (with Draft banner), "Save for later" to /home

- src/components/mdc/_theme.scss
- src/pages/_fallback.svelte
- --mdc-typography-button-font-weight to _theme.scss
- .mdc-button rule to _theme.scss
- _fallback.svelte content font-weight to use --mdc-typography-button-font-weight t
o
> Increase button and fallback font weight

- src/components/AppDrawer.svelte
- src/components/RoleAndPolicyMenu.svelte
- src/data/role-policy-selection.ts
- src/helpers/routes.ts
- src/pages/_layout.svelte
- Add rolePolicySelection store
- Refactor Role/Policy menu to record value in new store
- Fix adminRoleHome route (needed to be lowercase)
---
This doesn't quite get things working _correctly_, but it gets us closer.
Various facets of the challenge are...
- to properly initialize the Role/Policy menu (this mostly does so),
- to go to the appropriate page when the user manually changes the Roly/Policy menu's selection (this still does so),
- to properly handle situations where the user starts on a different policy's home page than their default Role/Policy menu selection (this doesn't do that yet), and
- to adjust the contents/destinations of the left nav menu based on the Role/Policy menu's selection (this doesn't do that yet, either).
> Extract role-policy-selection to a store

- src/components/RoleAndPolicyMenu.svelte
- src/data/role-policy-selection.ts
- src/pages/customer/home.svelte
- src/pages/policies/[policyId]/home.svelte
- Change our Role/Policy menu (and `$rolePolicySelection` store) to react to URL changes that include a `policyId` parameter _if_ the user is acting as a customer
- Fix some automatic redirects to avoid leaving browser history entries
---
This does not yet change the various places in the application that we use `$user.policy_id` to instead get it from the `$rolePolicySelection.selectedPolicyId`, but that's my next step.
> Treat any policyId in the URL as authoritative

- src/data/policies.ts
- Fix `account_detail` to be optional in `CreatePolicyRequestBody`
> Fix `account_detail` to be optional in `CreatePolicyRequestBody`

- src/pages/policies/[policyId]/claims/[claimId].svelte
- Was getting an error for adding actual values
- was getting a blank page after uploading a file
- The api needs to stop giving status: Receipt for FMV and Evacuation payoutOptions
> Receipt status cause bugs on Fmv & Evacuation

- src/components/Checkout.svelte
- Update Checkout component to use `$selectedPolicy` store
---
Previously, it (sometimes?) would lack some of the policy details, such as showing `undefined` for the Household ID.
> Update Checkout component to use `$selectedPolicy` store

- src/data/claims.ts
- src/pages/steward/home.svelte
- Fix steward home page to show the appropriate claim cards
- Fix list of claims awaiting each admin role to include Review3
- Enable getting (from the API) the claims awaiting a specific admin role
---
There's a bug in the API causing an admin's call to "GET /claims" to not return anything, but it works if we specify which status claims we want. We already have a list of which claims are awaiting each admin role (steward, signator), so this simply makes use of that and may help when merging the steward and signator home pages.
> Fix steward claim cards

- src/components/ClaimCard.svelte
- src/components/ClaimCards.svelte
- src/data/claims.ts
- src/pages/policies/[policyId]/claims.svelte
- src/pages/policies/[policyId]/items.svelte
- Refactor claim cards to use the item data provided with the claim data
- Update two uses of ClaimCards to stop passing in items 
I didn't update the admin home pages' uses because they'll be (re)moved in a forthcoming PR.
> Clean up claim cards

- src/components/ClaimActions.svelte
- src/data/claims.ts
- src/data/states.ts
- Add missing "Review3a" and "Review3b" statuses, where applicable
---
At the moment the backend is using "Review3", but the state diagram (and some discussion awhile back) indicates that it will be replaced with "Review3a" and "Review3b" statuses, to ensure that two different people sign off on payouts.
This PR just fills in the gaps so that we support all three options. Once the backend has been updated, we can remove the "Review3" status.
> Add missing "Review3a" and "Review3b" statuses, where applicable

- src/pages/_layout.svelte
- Don't show the "Add Item" button until we have a Policy ID
---
This prevents the user form going to the add-item page using a `null` Policy ID.
> Don't show the "Add Item" button until we have a Policy ID

- src/components/SearchableSelect.svelte
- src/pages/policies/[policyId]/settings.svelte
- Warn user to choose a valid entity code in settings (already happens at submit for new policy)
- clear Searchable Select input on focus so all datalist options are visible
- tweak styling
- add on:change to provide some user feedback when no selection is made
> validate entity code

- src/pages/policies/[policyId]/items.svelte
- Show friendlier text and an "Add Item" button for itemless policies
- If we already have items, show them even while reloading the items data
- Update policy items page to use `$selectedPolicyId` store
> Handle item-less policy display better

- src/data/policies.ts
- src/pages/policies/[policyId].svelte
- src/pages/policies/[policyId]/claims.svelte
- src/pages/policies/[policyId]/claims/[claimId].svelte
- src/pages/policies/[policyId]/items/[itemId].svelte
- Only calculate a policy name client-side if none was provided by the API
- Update UI code to be consistent about how it obtains a policy's name
> Fix policy-name code

- src/components/Breadcrumb.svelte
in some cases where we are dynamically constructing the breadcrumbs, not all values are on pageload (eg the policy household name). when we pass an empty node to the breadcrumbs component (even for a second) it will result in an exception being thrown and the entire page blowing up! kapow! this seems like a less than ideal situation. it might be better to just ignore invalid breadcrumb nodes until the reactive statement re-triggers and we have a value.
> remove exception from breadcrumbs component

- src/data/dependents.ts
- Actually call the API when we edit a policy dependent
- Actually call the API when we delete a policy dependent
> Actually call dependents API endpoints for edits and deletes

- src/components/ItemsTable.svelte
- src/components/RecentActivityTable.svelte
- The Header Item as well as Row Item needs to have `numeric` to align right.
- Material handles alignment as long as we do this.
> aligned numeric Datatable Items right

- src/components/CardsGrid.svelte
- src/components/ClaimCard.svelte
- src/components/ClaimCards.svelte
- src/components/ItemCard.svelte
- src/components/ItemDetails.svelte
- src/components/ItemsTable.svelte
- src/components/RecentActivityTable.svelte
- src/components/forms/ItemForm.svelte
- src/data/accountablePersons.ts
- src/data/dependents.ts
- src/data/items.ts
- src/data/policy-members.ts
- src/pages/admin/home.svelte
- src/pages/policies/[policyId].svelte
- src/pages/policies/[policyId]/claims.svelte
- src/pages/policies/[policyId]/claims/[claimId].svelte
- src/pages/policies/[policyId]/items.svelte
- src/pages/policies/[policyId]/items/[itemId].svelte
- src/pages/policies/[policyId]/items/[itemId]/edit.svelte
- src/pages/policies/[policyId]/items/new.svelte
- src/pages/policies/[policyId]/settings.svelte
- src/pages/policies/[policyId]/settings/dependents/[uuid].svelte
- src/pages/policies/[policyId]/settings/dependents/new.svelte
The response body for PolicyItems has changed such that 'accountable_person' now contains both the id and user-friendly name of the accountable person (instead of just an id). This means that we can rip up TONS of now-dead code that was doing fangaly data loads and look-up in order to retrieve this data.
The remaining places where we still need to do a load'n'look-up for policy dependent/member data is in the following cases
* when we are creating a new policy item
* when we are editing a policy item
* when we are editing policy settings and policy dependent settings
> remove accountablePersons from most components

- src/components/ClaimActions.svelte
- src/pages/policies/[policyId]/claims/[claimId].svelte
- We can skip `claim.status: Receipt` by using ClaimsApprove endpoint instead of PreApprove
- FMV and FixedFraction  don't require a receipt so we use ClaimsApprove
> approve FMV & FixedFraction instead of preapprove

- src/data/claims.ts
- src/data/states.ts
- Remove `Review3a` and `Review3b` statuses
- Update which claims statuses we show as awaiting each admin role
The new design is that Steward can do Review1 and Review2, and Signator can do Review3.
---
@hobbitronics, I did not modify the ClaimActions component, since it sounded like you would be handling those changes and they looked more involved that just removing entries from a list.
> Remove `Review3a`/`Review3b` and update claim statuses awaiting admins

- src/authn/session.ts
- src/components/App.svelte
- src/helpers/routes.ts
- src/pages/home.svelte
* keep track of the last route the user has visited and the time they visited
* the first time we arrive at the default home page (which is where the post-login process will drop a user) check if we should resume the prior "session"
> add session resume feature

- src/components/ClaimCard.svelte
- src/components/ItemCard.svelte
Now each card will auto expand to match the largest sibling's height in same row:
> fix(Card): Allow each policy card in each row to auto expand it's height

- src/components/AppDrawer.svelte
- src/pages/_layout.svelte
- remove Drawer menu items for admins as they all go to admin/home and cause the wrong item to be highlighted
- remove faq
- we may want to show a different view for them at some point but for now they seem to serve no purpose
> removed faq, Items and Claims from Admin roles

- src/authn/user.ts
- src/components/RoleAndPolicyMenu.svelte
- src/pages/_layout.svelte
- this allows the customer/admin to stay on a claim/item but change roles or stay on settings and change policy
- the customer will not be able to view the same claim/item when switching policies so will be sent to home
> stay on current page when changing role/policy

- src/authn/user.ts
- src/pages/home.svelte
- Remove the `UserAppRole.Admin` role
---
It has already been removed from the backend. This resolves the naming collision we had between an actual `Admin` role vs. our convention of referring to any Steward or Signator as an "admin".
> Remove the `UserAppRole.Admin` role

- src/data/countries.ts
- src/pages/settings/personal.svelte
- Add a `countries` svelte store, populated asynchronously when first used
- Change "Personal Settings" page to be a searchable-select of a list of countries
---
We'll probably want to extract this to a `<CountrySelector ... />` or something like that if we end up using this in multiple places (such as on the DependentForm). There were just enough details involved that I wouldn't want them replicated throughout our codebase.
> Use countries list from API

- src/components/AppDrawer.svelte
- src/components/RoleAndPolicyMenu.svelte
* resolves the issue where the app drawer resizes with a long team name
* instead it will now show as below (default behavior for a Button)
> remove auto-width from app drawer

- src/authn/user.ts
- src/data/policies.ts
* This resolves an issue where a policy name in the sidebar is not updated when a policy name change occurs
> Update the user store when updating a policy

- src/pages/_layout.svelte
- Use an open umbrella icon for the "Items" nav menu entry
> Fix umbrella icon in menu

- src/components/ClaimActions.svelte
- src/data/claims.ts
- src/pages/policies/[policyId]/claims/[claimId].svelte
on Claim view the Steward was seeing the wrong Approve button label due to a typo.
> fixed Approve button label & changed type to enum

- src/components/global.css
- src/pages/_fallback.svelte
- src/pages/policies/[policyId]/claims.svelte
- src/pages/policies/[policyId]/home.svelte
- src/pages/policies/[policyId]/items.svelte
- after adding p { max-width: 80ch}, pages with `<p>` for main content were not centered
- added m-0-auto to global.css and these pages
> center pages using <p> for main content

- src/components/NoHouseholdIdModal.svelte
- src/components/const.ts
- src/helpers/routes.ts
- src/pages/policies/[policyId].svelte
- src/pages/policies/[policyId]/settings.svelte
- src/pages/privacy.svelte
- src/pages/terms.svelte
- remove householdId form noHouseholdIdModal
- add message to contact cover@sil.org for householdId changes
- hide householdId field on 'policy/settings' view for customer
- add link to 'policy/settings' on policy view
- add a const and route for cover.sil.or
g
> don't allow customer to change household ID

- src/data/claims.ts
- src/pages/policies/[policyId]/claims/[claimId].svelte
- Use the new claimItem.coverage_amount instead of item.coverage_amount. 
- This is particularly important for Paid claims so that the amount displayed is the amount at the time of the claim rather than the current amount. 
-  Claims imported from RiskMan are greatly affected by this since the item's coverage amount was set to 0 when coverage was removed.
> use coverage_amount on claimItem

- src/business-rules/claim-payout-amount.ts
- src/components/forms/ClaimForm.svelte
- src/pages/policies/[policyId]/claims/[claimId].svelte
- show "save for later" alongside "continue"
- disable buttons when missing fields
- allow saving a draft claim without all the fields
> new-claim show save for later and disable buttons

- src/components/ClaimsTable.svelte
- src/components/index.ts
- src/pages/policies/[policyId].svelte
- src/pages/policies/[policyId]/claims.svelte
- Add (missing) table of claims to the claims page
---
Side note: We still seem to have an off-by-one error in the output of both `formatDate()` and `formatFriendlyDate()`, and I haven't had time (and probably won't have time) to fix that myself in the near future, if one of you two would be available to handle that.
> Fix claims page

- src/components/ClaimActions.svelte
- src/components/MoneyInput.svelte
- src/components/SearchableSelect.svelte
- src/components/const.ts
- src/components/forms/ClaimForm.svelte
- src/components/forms/DependentForm.svelte
- src/components/forms/ItemForm.svelte
- src/components/forms/SearchForm.svelte
- src/pages/policies/[policyId]/items/[itemId].svelte
- src/pages/policies/[policyId]/settings.svelte
- src/pages/policies/new.svelte
- src/pages/settings/personal.svelte
- added maxlength const
- set maxlength in all text/number inputs
- TextArea will now show how many characters are left TextField does not do this
- Added required prop to MoneyInput (did not use it yet in any instances)
- further changes will need to be made in ui-components
> add maxlength to text inputs

- rollup.config.js
"Rollup 'sourcemap' option must be set to generate source maps."
> resolve "Rollup 'sourcemap'" warning

- src/components/FilePreview/FilePreview.svelte
- src/pages/policies/[policyId]/claims/[claimId].svelte
Avoids warning on build:
```
[build:dev ] (!) Plugin svelte: FilePreview has unused export property 'isMemberOfPolicy'. If it is for external reference only, please consider using `export const isMemberOfPolicy`
[build:dev ] src/components/FilePreview/FilePreview.svelte
[build:dev ]  6: export let previews = [];
[build:dev ]  7: export let uploading = false;
[build:dev ]  8: export let isMemberOfPolicy = false;
[build:dev ]                ^
[build:dev ]  9: let selectedId = '';
[build:dev ] 10: const dispatch = createEventDispatcher();
```
> remove unused isMemberOfPolicy property from FilePreview

- src/pages/privacy.svelte
Eliminates the following warning:
```
[build:dev ] (!) Plugin svelte: Unused CSS selector "ul"
[build:dev ] src/pages/privacy.svelte
[build:dev ]  7: <style>
[build:dev ]  8: ol,
[build:dev ]  9: ul {
[build:dev ]     ^
[build:dev ] 10:   line-height: 1.5;
[build:dev ] 11: }
```
> remove unused selector

- src/pages/policies/[policyId].svelte
- moved ClaimTable above ItemTable
- show max 15 claims/items unless "All" button is clicked
- only show recent (1 mo) items
- add link to items at bottom
- limit card to 4 or 3 depending on screen size
> add buttons to show > 15 items/claims

- src/components/CardsGrid.svelte
- src/components/ItemsTable.svelte
- src/pages/policies/[policyId].svelte
- src/pages/policies/[policyId]/items.svelte
- make Items view filterable
- remove card
- combine active and inactive tables
- add cardLimit prop to CardsGrid
- use editableCoverageStatuses to show 'Edit' in menu
> Update items view

- src/components/Breadcrumb.svelte
- src/pages/policies/[policyId]/claims.svelte
- src/pages/policies/[policyId]/claims/[claimId].svelte
- src/pages/policies/[policyId]/items/[itemId].svelte
- Default to no home icon
- add umbrella and clipboard icons to items/claims
- code cleanup
> Remove home breadcrumb and add icons for claims/items

- src/pages/policies/[policyId]/claims.svelte
- src/pages/policies/[policyId]/items.svelte
- data not reloading when switching policies on claims/items views
- removed some unused code
- loading data in onMount no longer necessary
> fix data not reloading on policy change

- src/components/ItemDetails.svelte
- When accountable persons are deleted the "Accountable Person" and "Location" fields are empty
> Add placeholders in markup to handle blank fields

- src/components/forms/DependentForm.svelte
When adding a dependent to household policies "team" was being shown
> don't show team for household policy settings

- src/components/ClaimActions.svelte
- src/components/ConvertCurrencyLink.svelte
- src/components/Description.svelte
- src/components/SelectAccountablePerson.svelte
- src/components/TextFieldWithLabelAndDescription.svelte
- src/components/forms/ItemForm.svelte
- ItemForm uses new design mockup
- Notes (Description) not required anymore
- When adding a dependent then saving for later, the new dependent wasn't selected when going back to edit
> New itemform design and fix a bug

- src/components/ClaimsTable.svelte
- Remove "maximum"
- show "est." before incomplete `claim.payout`
> add "est." to incomplete claim payouts

- src/data/states.ts
- used `needsReview` state but modified the icon and title for `needsReceipt` state
> claim card should show "receipt" instead of "changes"

- src/components/FilePreview/FilePreview.svelte
- src/components/FilePreview/FilePreviews.svelte
- src/components/FilePreview/index.ts
- src/components/index.ts
- src/pages/policies/[policyId]/claims/[claimId].svelte
- src/pages/settings/personal.svelte
- refactor `FilePreview` into `FilePreview` and `FilePreviews` to decouple from `claims`
- use in personal settings to match design
> refactor FilePreview and use in personal settings

- src/components/Strikes.svelte
- src/components/index.ts
- src/data/policies.ts
- src/pages/policies/[policyId].svelte
- add basic ability to add and view strikes on a policy
- show and explain strikes to customer (basics for now)
Admin view
customer view
Hide the form
> Add strikes to policies

- src/components/CustomerReport.svelte
- src/data/ledger.ts
- src/pages/admin/reports.svelte
- fix adding an empty row to Policy Report Table
- add a store so PolicyReports get updated automatically
- add a notice for when no report is available
- get all ledger reports and filter down by user/`file.name` to initialize policyLedgerReports (this will help cut down on users creating excess reports since they will persist)
> add policyLedgerReports store and add notice

- src/components/Banner.svelte
- src/components/ClaimCard.svelte
- src/components/ClaimCardBanner.svelte
- src/components/ItemCard.svelte
Before
After
Alternative solution:
Just add some padding to the lower banner
> fix banner alignment

- src/pages/_layout.svelte
- If customer types in an admin url show them something else
> prevent customer from manually viewing admin page

- src/components/App.svelte
- I logged in after a `make fresh` and the Drawer remained invisible until I refreshed. The policy was probably just taking awhile.
- use `$user.id` instead of policies to check for authentication
- also hide the snackbar until after login so users don't see "you can't perform this action" while logging in
> Drawer was remaining invisible after login

- src/components/Checkout.svelte
- src/pages/policies/[policyId]/items/new.svelte
- adding 20% padding to the right of the checkout button to prevent total overlap with freshdesk button
- send to editItem so new item isn't created again
> fix checkout duplicate item bug and button overlapping with freshdesk

- src/business-rules/claim-payout-amount.ts
- src/components/forms/ClaimForm.svelte
- src/pages/policies/[policyId]/claims/[claimId].svelte
- Stop using built in TextInput labels
- fix ClaimId view bug for FMV claims where repairable is selected but estimate is too high and unable to submit
> Remove labels claim form and fix bug

- src/components/Datatable/ItemsTable.svelte
- src/data/states.ts
- src/pages/policies/[policyId].svelte
- Change the itemStates.title from "Approved" item to "Active"
- use the `itemState.title` rather than the `item.coverage_status` in markup
> Change "Approved" item to "Active"

- src/components/RemoveDependentModal.svelte
- src/components/RemoveMemberModal.svelte
- src/components/forms/DependentForm.svelte
- src/components/index.ts
- src/data/items.ts
- src/data/policy-members.ts
- src/data/types/policy-members.ts
- src/pages/policies/[policyId]/settings.svelte
- added a basic modal for removing a member (similar to dependents modal)
- changed isDependentOnItemsByPolicyId to howManyItemsAccountablePersonIsOn
- fixed some imports
- added a delete button for policy-members in settings (excluding self)
> add RemoveMemberModal

- src/components/Checkout.svelte
- src/components/forms/ItemForm.svelte
- src/helpers/routes.ts
- src/pages/policies/[policyId]/items/[itemId]/checkout.svelte
- src/pages/policies/[policyId]/items/[itemId]/edit.svelte
- src/pages/policies/[policyId]/items/new.svelte
- Make checkout its own page to preserve history
- add autosaving to ItemForm with debounce
- new -> edit on ItemForm autosave so when user click 🔙  they go to edit with data preserved
some notes:
when creating a new item once category and name are filled out and 4 sec of inactivity the user is taking to edit, but page scroll and focus are not preserved in ItemForm. Is there a way around this?
I failed to capture clicking the back button in the frame and that the form does indeed start on new.
> Preserve history on checkout

- src/components/NewCoverageModal.svelte
- src/components/index.ts
- src/data/items.ts
- src/pages/policies/[policyId]/claims/[claimId].svelte
- Add modal to offer new coverage for replaced items after uploading replace receipt
- create a new item with the old item's data
- send the user to itemEdit to edit the new item
> add NewCoverageModal to claim view

- src/components/forms/ItemForm.svelte
- src/components/index.ts
- src/data/items.ts
- src/helpers/routes.ts
- src/pages/policies/[policyId].svelte
- src/pages/policies/[policyId]/items/[itemId]/checkout.svelte
- src/pages/policies/[policyId]/items/new.svelte
- added a qs for ItemId in ItemsNew
- fixed a bug (on my machine anyways) where Checkout wasn't importing properly
- fixed a bug where policyId was undefined
To summarize now can can go to ItemsNew, fill it out (minimum of name and category for it to create an item), navigate to Checkout or anywhere else, click 🔙   and arrive back at `ItemsNew` with the data still intact.
> preserve new item data with qs

- src/components/BatchItemDelete.svelte
- src/components/Datatable/ItemsTable.svelte
- show "delete" on button when only Drafts are selected
- otherwise continue showing "End Coverage"
> optimize batch item delete label

- src/components/BatchItemClone.svelte
- src/components/BatchItemDelete.svelte
- src/components/Datatable/ItemsTable.svelte
- Disable Batch Delete when ended items selected
- Assert no open claims on items being deleted
- make item.status column red in ItemsTable to draw attention that coverage cancellation has already happened
> Disable Batch Delete when ended items selected and assert no open claims

- src/pages/_layout.svelte
- when switching from Customer to Admin or opposite from Items or Claims views, would get a bad url
> fix bad url bug

- src/pages/settings/personal.svelte
- Added buttons to personal settings
- custom_email gets saved when either "save" or "save changes" is clicked rather than on:blur
see https://trello.com/c/znDg06sW/245-add-save-changes-button-to-the-bottom-of-settings-pages-tell-user-about-autosave-onclick
> add save, save changes and discard button to personal settings

- src/components/RadioOptions.svelte
- src/pages/admin/home.svelte
- refactored so Claims are guaranteed at the beginning of the array in recent changes on admin/home
- For Signators Claims willl only be of status `Review3` so they will be first. Stewards don't see these
see https://trello.com/c/4dKEP19z/399-for-stewards-reorder-action-cards-on-home
> Sort recent changes

- src/components/Datatable/ItemsTable.svelte
- src/components/progress/index.ts
- src/data/audits.ts
- src/data/claims.ts
- src/data/items.ts
- src/helpers/routes.ts
- src/pages/_layout.svelte
- src/pages/admin/_components/AuditsOrRepairTable.svelte
- src/pages/admin/audits.svelte
- src/validation/assertions.ts
- add /audits view
- add buttons to run audits and repairs
- add tables to show items found in audits and repairs
After the audit result has loaded
After running the repair
Item had an active claim
To help admin find claims if action is needed
> audit renewals

- Makefile
- src/pages/policies/new.svelte
- Switch from using `docker-compose up` to `docker-compose run` for the `make docker` command.
- Filter out inactive and household entity codes for new policy form.
> hide inactive entities

- src/components/ConvertCurrencyLink.svelte
- src/components/forms/ItemForm.svelte
- src/components/forms/items/itemFormHelpers.ts
- prevent allowing `0` for `marketValue`
- move functions to a helper file
- fix a warning
> fix ItemForm allowing 0, move functions

- src/data/items.ts
- src/helpers/money.ts
[CVR-607](https://itse.youtrack.cloud/issue/CVR-607/Coverage-amount-not-accepted-because-it-is-not-an-integer)
> CVR-607  fix submitting a float instead of int on items

- src/data/ledger.ts
- src/pages/admin/reports/[reportId].svelte
[CVR-613](https://itse.youtrack.cloud/issue/CVR-613) On the admin report page, add a new file download line. Describe the difference between the different downloads:
- The original download is for Sage and will give a CSV of all transactions (as before)
- The second download is for NetSuite and will give a ZIP of transactions split into different CSVs by type. I added a field to ReportLedger for this file, which will need to be populated before release (TODO @jason-jackson).
I also improved the semantics and formatting of the page.
There was already a bug where the file link will sometimes stop being a link. Even though it loads as a link, when I go away and come back, it's no longer a link—not clickable, blue, or underlined! I don't know whether it had been reported or now. I haven't …
> Feature/report csv+zip

- src/components/AppDrawer.svelte
[CVR-655](https://itse.youtrack.cloud/issue/CVR-655/Why-drawer-menu-items-have-extra-margin)
> less margin between drawer menu items CVR-655

- src/components/Datatable/PolicyItems/ItemsTable.svelte
- I couldn't use the full Datatable.Row component because mdc was throwing an error which I could not decipher.
> add row with None in ItemsTable

- src/components/checkout/YearlyCheckoutMessage.svelte
- CVR-705 (b): Fix incorrect reliance on `coverage_start_date` before approval
> CVR-705 (b): Fix incorrect reliance on coverage_start_date before approval

- src/components/ItemDetails.svelte
- src/components/checkout/MonthlyCheckoutMessage.svelte
- src/components/forms/ItemForm.svelte
- src/data/items.ts
- src/helpers/coverage.ts
- src/helpers/dates.ts
- Fix start-date calculations used for checkout page (re: monthly vs yearly)
- Fix renewal-date calculations used for checkout page (re: monthly vs yearly)
- Fix `formatDate()` to treat Go empty-date values as not a date
- Add `getPremiumDescription()` helper
- Add `getRenewalDate()` helper
- Add `getStartDate()` helper
- Add `isBeforeMonthlyCutoff()` helper
- Add `isItemDraft()` helper
- Add `isMeaningfulDateString()` helper
- Add `isMonthly()` helper
- Add `startOfFutureMonth()` helper
> CVR-705 (c): Update other checkout details re: monthly vs yearly

- src/components/Datatable/PolicyItems/ItemsTable.svelte
- src/helpers/coverage.ts
- When sorting by premium, use the field being displayed 
* Previously it was sorting by `prorated_annual_premium`, but displaying `annual_premium`. If that was intentional, please let me know.
- For items billed monthly, show that in the Items Table
---
I wrestled a little bit with various ways to handle showing annual vs. monthly premiums. This approach seems to work, since it both (A) visually indicates which are paid monthly, and what that monthy amount is, and (B) still shows the annual premium so that sorting the table by the Premium column still produces results that make sense (since the primary number shown is the annual premium, even for items billed monthly).
> CVR-705 (d): Update the Items Table re: monthly vs yearly billing periods

- .vscode/settings.json
- src/components/checkout/MonthlyCheckoutMessage.svelte
- src/components/checkout/YearlyCheckoutMessage.svelte
- src/data/itemCategories.ts
- src/data/items.ts
- src/helpers/coverage.ts
- src/helpers/money.ts
[CVR-736](https://itse.youtrack.cloud/issue/CVR-736/Update-UI-to-reflect-the-minimum-premium)
[CVR-737](https://itse.youtrack.cloud/issue/CVR-737/Update-UI-logic-to-reflect-that-the-minimum-premium-applies-to-both-the-annual-premium-and-the-prorated-annual-premium)
- prettier not formatting again
- isBeforeMonthlyCutoff value was being used
- ts errors
- ItemCategory to PolicyItem
- Yearly checkout message to show minimum and always show payment
> CVR-736 CVR-737 Add minimum premium to checkout and update ItemCategory

- src/components/InfoDialog.svelte
- src/components/InfoModal.svelte
- src/components/index.ts
- src/pages/policies/[policyId].svelte
[CVR-705](https://itse.youtrack.cloud/issue/CVR-705/Update-UI-to-handle-monthly-vs-yearly-premiums)
- Added InfoDialog
- Added Monthly Premium (sum of all) to policy details
> CVR-705 Add monthly premiums to policy page

- src/components/forms/ItemForm.svelte
- src/components/forms/items/itemFormHelpers.ts
- src/data/items.ts
- Use "coverage value" not "market value" in validation message
- Rename ItemForm-related `marketValueUSD` to `coverageAmountUSD`
> CVR-747: Use "coverage value" not "market value" in validation message

- src/data/items.ts
- src/helpers/coverage.ts
- Show "when approved" as start date if an item's status is Pending (not just Draft)
- Show renewal date for monthly items with a status of Pending (not just Draft)
> CVR-749: Fix display of "Starts" and "Renews" fields when monthly approval is pending

- src/components/forms/ItemForm.svelte
- Fix the condition for when to show the Delete button on an Item Form
---
I once again tested a function instead of calling it. I think this was leftover from a rename I did, where I apparently missed this occurrence.
> Fix the condition for when to show the Delete button on an Item Form

- src/helpers/money.ts
- Use browsers' built-in currency formatting, to get thousands separators
> Use browsers' built-in currency formatting, to get thousands separators

- src/helpers/coverage.ts
- src/pages/policies/[policyId].svelte
[CVR-761](https://itse.youtrack.cloud/issue/CVR-761) Fix monthly premium total
---
- Fix monthly premium total on Policy details page
---
When running it locally, I was seeing a monthly premium of $13.33 that should have been $12.50. On further inspection, it looks like even annually-billed items (at least sometimes) have a monthly_premium value.
Breaking it out to get the lists of (approved) annual and monthly items first, then summing them, seems to have fixed it.
> Fix monthly premium total

- src/components/ItemDetails.svelte
- src/data/items.ts
- src/helpers/dates.ts
- Fix possilby showing renew dates on Inactive items
- show date information more consistently like in ItemsTable
[CVR-667](https://itse.youtrack.cloud/issue/CVR-667)
> show dates like in table CVR-667

- src/components/Datatable/PolicyItems/ItemsTable.svelte
- src/data/items.ts
- src/helpers/sort.ts
- src/pages/policies/[policyId].svelte
- add a checkbox to hide non vehicles
- sort Items by Vehicles first as default
[CVR-786](https://itse.youtrack.cloud/issue/CVR-786)
> sort vehicles to top and add hide button CVR-786

- src/components/RoleAndPolicyMenu.svelte
- src/components/mdc/types/MenuItem.ts
- src/helpers/dates.ts
- a button in the `RoleAndPolicyMenu` to hide or show policies that have not been updated 30 days
[CVR-50](https://itse.youtrack.cloud/issue/CVR-50)
default menu shows all policies
> add hide/show policies menu button CVR-50

- src/pages/policies/new.svelte
- New team policy breadcrumb as /policies only exists for admins
> fix new policy breadcrumb

- src/components/FileLink.svelte
- fix failed render by opening file download in separate tab
[CVR-666](https://itse.youtrack.cloud/issue/CVR-666)
> open download in own tab to fix bad request CVR-666
