silinternational/cover-ui

- src/components/global.css
- src/pages/_layout.svelte
- added drawer and fixed layout
- moved css rule to body
- arrange imports and remove extra {}
- made Drawer menu narrower - will work with ui-components update as no class prop now
- capitalize menu items
> Add Drawer to _layout.svelte

- src/components/DependentForm.svelte
- src/pages/household/settings/dependent.svelte
- Add a simple "add-dependent" form
> Simple "add dependent" form

- dist/index.html
- Stop registering a service worker for now
> Don't set up a service worker yet

- package-lock.json
- package.json
- src/pages/_layout.svelte
updated ui-components
@hobbitronics
made "add item" a button - still needs some polishing but this will be done in the Drawer component
removed scroll in menu by setting isFullHeightMenu to false.
> Add button to drawer menu

- src/components/typography.scss
- Specify font family to use app-wide
> Typography

- src/components/Breadcrumb.svelte
- Replace dashes with spaces in breadcrumbs' display text
> Fix dashes in breadcrumbs

- src/components/Description.svelte
- src/components/RadioOptions.svelte
- src/pages/add-coverage/new-item.svelte
- Add basic form for requesting coverage for a new item
> Add coverage  / new item

- src/pages/add-coverage/new-item.svelte
- Change "Accountable person" to be a drop-down
> Clean up of "add coverage" form

- src/pages/_layout.svelte
- Change "Policies" to "Home" in menu
> Change "Policies" to "Home" in menu

- src/components/Breadcrumb.svelte
- src/pages/household/settings/index.svelte
- Build some bottom-margin into the Breadcrumb component itself
- Rename "Members" to "Accountable people"
- Simplify display code slightly
> Update household settings

- src/components/App.svelte
- src/components/global.css
- src/components/mdc/_theme.scss
- src/pages/_layout.svelte
Removed TopAppBar
changed background color in Drawer content
added theme color - may not be accurate yet!
> Removed TopAppBar Drawer border color and changed background color

- src/components/AppHeader.svelte
- src/pages/_layout.svelte
- fixed icon url
- remade header with Avatar and hamburger button
> remake header

- src/components/DependentForm.svelte
- src/components/RadioOptions.svelte
- src/pages/household/settings/dependent.svelte
- src/pages/household/settings/dependent/[uuid].svelte
- src/pages/household/settings/index.svelte
- Add new fields to "dependent" form
- Enable editing a dependent
- Stop using `<p>` tags inside RadioOptions component
> Update our "Dependent" form

- src/pages/claims/[itemId]/new-claim.svelte
Added the logic for the form and modified spacing a bit.
> Revamped claim form

- package.json
- Change port used for local development
---
This avoids a port conflict when also running the API locally.
> Change port used for local development

- src/pages/_layout.svelte
- src/pages/home.svelte
- src/pages/index.svelte
- Move home page content to "home.svelte"
---
This frees up "index.svelte" to use for initial user auth on arrival. The contents of "home.svelte" and "index.svelte" were merely swapped unchanged, to keep this PR simple to review.
> Move home page content to "home.svelte"

- src/components/ClaimCard.svelte
- src/pages/_layout.svelte
- src/pages/home.svelte
used breakpoints and grid classes to:
- make the card grid responsive
- make the cards responsive
> made ClaimCards grid responsive

- src/authn/index.js
- src/authn/token.js
- src/authn/user.js
- src/components/App.svelte
- src/components/AppHeader.svelte
- src/data/index.js
- src/data/user.js
- src/i18n/index.js
- src/i18n/phrases.json
- src/pages/index.svelte
- Add authentication, but fake it for the moment
> Fake authentication

- src/authn/index.js
- Prevent auth redirect while we're faking authentication
> Prevent auth redirect while we're faking authentication

- src/components/ClaimCard.svelte
- src/pages/home.svelte
- imported Page into Home
- set rows
- cleaned up some spacing and css
> revamp home layout

- src/pages/_fallback.svelte
- Add a robot emoji to our 404 message
- Center our 404 message
> Center our 404 message and add a robot emoji

- src/components/AppHeader.svelte
- Fix user field names in AppHeader
> Fix user field names in AppHeader

- src/components/ClaimCards.svelte
- src/components/index.js
- src/components/mdc/Row.svelte
- src/pages/claims.svelte
- src/pages/home.svelte
- card layout as per designers intent
- created Row and ClaimCards components
- added Row, ClaimCards and ClaimCard to index
- imported Row to home and claims
- added ClaimCards to claims page
- added state to example item
> claims page

- src/components/mdc/_theme.scss
- src/data/claims.js
added states object
added theme colors
> Add claim states static resource

- src/components/ClaimCard.svelte
- src/components/ClaimCards.svelte
- src/components/mdc/_theme.scss
- src/data/claims.js
- src/pages/home.svelte
- add state properties to claimCard
- rename items, add getState function
- set exampleItems state and fix typo
- added neutral variant colors
- used colors from theme
> Incorporate claim card states

- src/components/DependentForm.svelte
- src/data/claims.js
- src/data/dependents.js
- src/data/itemCategories.js
- src/data/items.js
- src/data/policies.js
- src/pages/household/settings.svelte
- src/pages/household/settings/dependent.svelte
- src/pages/household/settings/dependent/[uuid].svelte
- Actually send the add-dependent data to the API
> Enable adding a dependent via API calls

- src/components/banners/SuccessBanner.svelte
- src/components/banners/WarningBanner.svelte
- src/components/index.js
- src/components/mdc/_theme.scss
- src/pages/claims/[claimId].svelte
- Add helper components for success and warning banners
- Add a dummy claim-details page
> Claim details page

- src/components/progress/Progress.svelte
- import Linear into progress
- add indeterminate
- use global classes
> upgrade progress

- src/components/global.css
- src/components/progress/index.js
- src/components/table/Table.svelte
- src/data/claims.js
- src/data/dependents.js
- src/data/items.js
- src/data/policies.js
- src/pages/home.svelte
used loading store from /components/progress/index.js and its functions start and stop.
here's an example of how it works https://codepen.io/midotron/pen/gOWqQWK?editors=1111
> Centralize loading

- src/authn/index.js
- src/authn/token.js
- src/components/App.svelte
- src/pages/logged-out.svelte
- src/pages/logout.svelte
- src/pages/welcome.svelte
- Use real authentication instead of faking it
- Fix the login redirect to call a method on location, not assign to it
- If the user reaches "/logged-out" while logged in, log them out
- Convert tabs to spaces in App.svelte
- For now, just redirect the user from "/welcome" to "/home"
> SAML authentication

- README.md
- src/components/ClaimCard.svelte
- src/components/ClaimCards.svelte
- src/data/claims.js
- src/data/items.js
- src/pages/claims.svelte
- src/pages/claims/newClaim.svelte
- src/pages/home.svelte
- src/pages/household/settings.svelte
- src/pages/items/[itemId].svelte
- src/pages/items/[itemId]/new-claim.svelte
- src/pages/items/new.svelte
- createClaim call
- getItems call
- loadPolicies call and fix $user syntax
- cleaned up some code and fixed lots of bugs
> Get createClaims working

- .gitignore
- README.md
- src/components/ClaimCard.svelte
- src/components/ClaimCards.svelte
- src/data/claims.js
- src/data/items.js
- src/pages/claims.svelte
- src/pages/claims/newClaim.svelte
- src/pages/home.svelte
- src/pages/household/settings.svelte
- src/pages/items/[itemId].svelte
- src/pages/items/[itemId]/new-claim.svelte
- src/pages/items/new.svelte
call the api for getClaim() instead of use store
> claimsView endpoint call

- src/components/ClaimCard.svelte
- src/components/const.js
add const.js and import days to ClaimCard
calculate daysAgo
fix markup (I deleted the quotes shown in the screenshot but tore down my mock data already)
> calculate and show daysAgo

- src/components/AppHeader.svelte
- Remove unknown `autofocus` prop from Menu
> Menu cleanup

- src/data/claims.js
- src/data/policies.js
- src/pages/items/new.svelte
Since we should only be making one loadClaims or loadPolices call at a time, a static id should do.
> Use a static id instead of generic loading

- src/pages/items/new.svelte
Note: This does not yet pre-select the current user, because I was having some weird issues with that.
> Include policy members in accountable-persons dropdown

- src/data/items.js
- src/pages/home.svelte
- Fix updating of items store in addItems()
- Properly show items' names on the home screen
> Small fixes re: items

- src/data/claims.js
- src/pages/claims.svelte
- Ensure claims data is loaded when visiting the claims page
> Ensure claims data is loaded when visiting the claims page

- src/data/items.js
- src/pages/home.svelte
- src/pages/items/[itemId].svelte
- src/pages/items/[itemId]/new-claim.svelte
- Refactor items store to be grouped by policy ID
- Update home page to use items-by-policy-id
- Update item-details page to use items-by-policy-id
- Update new-claim page to use items-by-policy-id
> Group items data by policy ID

- src/data/claims.js
- updateClaim now calls the api
- added TODO comments
> finish updateClaim

- .env.example
- README.md
- dist/index.html
- package-lock.json
- package.json
- Update docs, package.json, etc. to reflect rename from "riskman-ui" to "cover-ui"
> Change uses of "riskman" to "cover"

- README.md
- Fix minor capitalization and formatting issues in README
---
This is primarily to trigger another build to our staging environment.
> Do some minor cleanup and reformatting of the README file

- src/components/ClaimCard.svelte
- src/components/banners/ClaimBanner.svelte
- src/components/dates.js
- src/data/claims.js
- src/pages/claims/[claimId].svelte
Replaced static content with real data
added dates.js
changed getState parameter from claim to claim.status
renamed some states to match api
> Real data in claim view

- src/pages/household/settings.svelte
- Added to settings view:
- TextField
- Snackbar
- call to updatePolicy endpoint
> added householdId field to settings

- src/components/SearchableSelect.svelte
- src/components/index.js
- src/pages/household/settings.svelte
Changed:
moved datalist to SearchableSelect component
> SearchableSelect component

- package-lock.json
- package.json
- src/components/forms/ItemForm.svelte
- src/data/items.js
- src/pages/home.svelte
- src/pages/items/[itemId]/edit.svelte
- Enable editing an item
- Key the each loop (of items) on the home page
- Detect if we ever try to update an item not in our local store
- Update dependencies
- Use a separate variable, loaded later, for setting the initial category in `ItemForm`
- Rename several variables to conform to lowerCamelCasing convention
- Move `itemId` to separate parameter to `updateItem()` method
- Change to match the new way the API returns the category ID
> Enable editing an item

- src/pages/household/settings.svelte
Added
- updateCostCenter
- updateHouseholdId
Removed
-updateGenericId
> Settings cost center revision

- src/data/claims.js
- src/pages/claims/[claimId].svelte
- updateClaimItem
- onBlur
- TODO
> Add updateClaimItem

- src/components/FileDropArea/FileDropArea.svelte
- src/components/FileDropArea/_index.scss
- src/pages/claims/[claimId].svelte
> animate FileDropArea previews

- src/components/forms/ItemForm.svelte
- src/data/items.js
> Add accountable_person_id to addItem and updateItem

- src/pages/home.svelte
- Replaced the non-exisitng properties in the home item table
> Real data in home item table

- src/components/Banner.svelte
- src/components/Breadcrumb.svelte
- src/components/mdc/_theme.scss
- src/pages/items/[itemId].svelte
Added real data that was either missing or faked.
Changed the layout and styling to match the mockup as shown below.
before:
after:
@forevermatt I changed the Remove button as seen below.
> Item details restyle and more data

- src/data/policies.js
- src/pages/household/settings.svelte
- relocated affiliations to policies.js
- AffiliationChoice was not declared or used to set choice
> Move affiliations store and bugfix

- src/components/ClaimCards.svelte
- src/helpers/date.ts
- src/pages/policies/[policyId].svelte
- Add formatFriendlyDate() helper
- Add basic policy-details page, with links to claim details
- Prevent error from trying to get properties of an item that wasn't found
> Policy details page

- src/customTypes/@silintl/ui-components.d.ts
- tsconfig.json
* the correct way to do this would be to add types to the library
* this works as a bandaid for now
> created types for ui-components

- src/data/items.ts
Calls the PolicyItemsSubmit endpoint
> added submitItem to items.ts

- src/pages/claims/[claimId].svelte
- src/pages/home.svelte
- src/pages/items/[itemId]/edit.svelte
- src/pages/items/new.svelte
my own bad merge between PR 141 and 144 introduced some regressions on the import lines. fix these
> fix issues caused by a bad merge

- src/pages/items/new.svelte
Yet another regression was introduced in PR#145 in the form of a missing include.
better manual testing was done this time. Q_Q
just shoot me now
> add missing include to items/new

- src/business-rules/claim-payout-amount.ts
- src/pages/claims/[claimId].svelte
I might have moved more to business-rules but wanted to keep it short.
I also fixed a but where Math.min() was choking on undefined.
> moved determineMaxPayout to business-rules

- src/pages/settings/personal.svelte
Not on the roadmap, so removing it. If commenting it out is preferred, let me know.
This is what it looks like for an admin:
> remove "Receive notification emails for" from user profile

- src/components/Error.svelte
- src/data/claim-incident-types.ts
- src/data/claims.ts
- src/data/dependents.ts
- src/data/index.ts
- src/data/itemCategories.ts
- src/data/items.ts
- src/data/policies.ts
- src/data/policy-members.ts
- src/error/index.ts
- src/pages/items/[itemId]/new-claim.svelte
* also improve the error message system
* also add return values on some API call that were lacking them. this will make testing easier down the road
* also add a few type in files i was editing anyways
> remove extraneous calls to start/stop progress bar

- src/components/mdc/_theme.scss
- src/customTypes/@silintl/ui-components.d.ts
- src/data/index.ts
- src/pages/items/[itemId].svelte
Added a dialog and called the remove endpoint
> Remove coverage

- src/pages/home.svelte
- accountable person was not showing
> Show accountable person on home page

- src/data/states.ts
- src/pages/claims/[claimId].svelte
- src/pages/home.svelte
- Fixed loadClaims bug
- renamed "Draft2" claimState to "DraftSecondary"
- added "Review1Secondary" claimState
> fix loading claims bug and add/rename secondary claim banner

- src/components/ClaimActions.svelte
- src/data/claims.ts
- src/pages/claims/[claimId].svelte
- Switch "Approve" button to "Pre-approve" for `Review1` claims
> Switch "Approve" button to "Pre-approve" for `Review1` claims

- src/components/forms/ItemForm.svelte
- src/data/accountablePersons.ts
- src/data/items.ts
- src/pages/home.svelte
- src/pages/items/[itemId].svelte
- accountablePersons.ts with helper functions
- accountable person not showing in item view and home item table
- accountable person not loading in edit/item
I was playing around with different ways of doing the same thing here so we may want to pick one and get rid of any unnecessary helpers
> accountablePerson in home, item and itemForm

- src/components/forms/ItemForm.svelte
- src/pages/items/[itemId]/edit.svelte
- src/pages/items/new.svelte
Move api call from itemForm to new and edit files.
> Move api calls from itemForm to page level

- src/authn/index.ts
- src/components/App.svelte
- src/pages/invite/[uuid].svelte
- Add "/invite/[uuid].svelte" page
- Do a slightly different login call for that page
- Only call `loadUser()` for non-public pages
> Add landing page for "invitation" links

- src/components/ClaimCard.svelte
- src/components/ClaimCards.svelte
- src/components/home/UserHomePage.svelte
- src/pages/claims.svelte
Get AccountablePersons in Claims page and Home to pass to ClaimCard
> Accountable person missing from ClaimCard

- src/components/global.css
- src/pages/claims/[claimId].svelte
- src/pages/items/[itemId].svelte
- break-word class 
- apply to claimId & itemId fields to fix overflowing
> fix overflowing fields in claimId & itemId

- src/components/AppDrawer.svelte
- src/components/index.ts
- src/pages/_layout.svelte
- Extract our usage of the Drawer to a local component for easier reuse
---
This will make it easier to have different menu items for customer, steward, and signator.
> AppDrawer component

- src/data/states.ts
- src/pages/customer/claims/[claimId].svelte
- src/pages/items/[itemId].svelte
Loaded policies, dependents, members and added missing fields.
Styled according to mockup.
Changed title of itemStates.Pending and claimStates.Review1, Review2, Review3.
mockup:
screenshot:
> Implement claim view design and tweak item view

- src/components/forms/ItemForm.svelte
- src/pages/items/[itemId].svelte
* remove validator requirement
* hide serial_number when not set
> fix item unique identifier validator

- package-lock.json
- package.json
- Font no longer Noto Sans in TextArea or TextField
- Menu now supports actions
- updated some patched dependencies
> updated ui-components and a few other deps

- src/components/mdc/_typography.scss
- updated table header font weight in typography
> Increase table header font weight

- src/data/items.ts
- src/pages/_layout.svelte
- src/pages/customer/claims.svelte
- src/pages/customer/home/[policyId].svelte
also fix some breadcrumbs and sidebar
> sort policy items by updated date

- src/components/Banner.svelte
- src/components/banners/ClaimBanner.svelte
- src/data/states.ts
- src/pages/policies/[policyId]/claims/[claimId].svelte
- I noticed the customer and admin see different banner while looking at the same claim
> add adminClaimStates and fix actual cost update bug

- src/components/FilePreview/FilePreview.svelte
- src/components/global.css
- src/pages/policies/[policyId]/claims/[claimId].svelte
- add and use isFileUploadedByPurpose instead of just checking claimFiles length
- show a banner with purpose to admin instead of Delete button
- open files in new tab
- make cursor and background color change when hovering over FilePreview to show its clickable
- fix a number of ts errors/warnings
> improve file preview

- src/data/index.ts
- src/pages/policies/[policyId].svelte
- src/pages/policies/[policyId]/claims/[claimId]/edit.svelte
- src/pages/policies/[policyId]/items.svelte
- Refactor isLoadingById() data to use relative API paths
- Fix usage of isLoadingById() to have correct paths and react better
> Fix `isLoadingById()`

- src/pages/signator/home.svelte
- src/pages/steward/home.svelte
- Label the admins' "Recent activity" table
> Label the admins' "Recent activity" table

- src/components/RoleAndPolicyMenu.svelte
- src/data/policies.ts
- src/pages/admin/policies.svelte
- src/pages/policies/[policyId].svelte
- Use new `policy.name` field for corporate policies
> Use new `policy.name` field for corporate policies

- src/components/ItemDetails.svelte
- src/components/banners/ItemBanner.svelte
- src/data/states.ts
- src/pages/policies/[policyId]/items/[itemId].svelte
- Admin should see "Awaiting changes" in gray
- Customer should see "Needs Changes" in orange
> corrected revision state for banners

- src/authn/user.ts
- src/components/RoleAndPolicyMenu.svelte
- src/helpers/routes.ts
- src/pages/_layout.svelte
- src/pages/home.svelte
- src/pages/policies/[policyId]/claims.svelte
- src/pages/policies/[policyId]/claims/[claimId].svelte
- src/pages/policies/[policyId]/items/[itemId].svelte
* remove AdminAppRole type and make UserAppRole an enum
* Update all hard-coded referenecs of app roles to use enum
> rename customer user role from 'User' to 'Customer'

- src/components/forms/SearchForm.svelte
- src/components/index.ts
- src/data/policies.ts
- src/data/query-string.ts
- src/helpers/routes.ts
- src/pages/admin/policies.svelte
- Fix admins' "policy search" feature
- Rename store holding query string data to urlQuery
> Fix admins' "policy search" feature

- src/authn/user.ts
- src/components/ClaimActions.svelte
- src/components/ItemDetails.svelte
- src/components/index.ts
- src/data/states.ts
- src/pages/policies/[policyId]/claims.svelte
- src/pages/policies/[policyId]/claims/[claimId].svelte
- src/pages/policies/[policyId]/items/[itemId].svelte
- added 'Admin' to UserAppRole as its in the api (not sure what its use case is)
- added ItemDetails to index
- updated adminItemStates.Pending
- use $roleSelection for isAdmin
> use role selection instead of app role

- src/components/RoleAndPolicyMenu.svelte
- src/data/policies.ts
- src/pages/admin/policies.svelte
- src/pages/policies/[policyId].svelte
- src/pages/policies/[policyId]/items.svelte
- Extract shared method for getting the name of a Policy
- Show the name of the policy at the top of its "home" page (items)
> Show policy title above list of covered items

- src/components/ClaimCard.svelte
- src/components/ClaimCards.svelte
- src/data/states.ts
- src/pages/policies/[policyId]/claims.svelte
- src/pages/signator/home.svelte
- src/pages/steward/home.svelte
- use $roleSelection to get the correct state
- add isAdmin as a prop to ClaimCards and set for admin home pages
- refactor some claimStates
> get correct claim card banner for admin

- src/components/ItemDetails.svelte
- src/data/entityCodes.ts
- src/data/policies.ts
- src/pages/policies/[policyId]/settings.svelte
- src/pages/policies/new.svelte
- used SearchableSelect to suggest entity codes
- fixed circular dependency
> get entity codes from api and suggest in corporate policy form

- src/components/SearchableSelect.svelte
- src/data/policies.ts
- src/pages/policies/[policyId]/settings.svelte
- src/pages/policies/new.svelte
- added all the fields that might be accepted by the endpoint
- made them optional in the Type
- show the key and dispatch the value in SearchableSelect
> add fields to settings for corporate policies

- src/components/ClaimCards.svelte
- src/data/claims.ts
- Only show claim cards that are about incomplete and/or recent claims
- Update ClaimItemStatus possible values
> Filter claim cards to those that are recent or incomplete

- src/components/App.svelte
- src/helpers/routes.ts
- src/pages/_layout.svelte
- src/pages/privacy.svelte
- Add "Privacy Policy" page (with placeholder text, not real content)
> Add "Privacy Policy" page (with placeholder text, not real content)

- src/components/RoleAndPolicyMenu.svelte
- src/pages/customer/home.svelte
- src/pages/home.svelte
- Wait to set initial role selection until we have the user's actual role
- Send admins to the admin home page by default
- Default the customer to a corporate policy if they have one, household if not
> Fix "/home" redirects

- src/components/SearchableSelect.svelte
I realized after one of recent PR's I could eliminate the for of loop
> remove for of loop

- src/data/policies.ts
- src/pages/_layout.svelte
- src/pages/policies/[policyId]/settings.svelte
- src/pages/policies/new.svelte
- Change "Group" to "Policy" throughout the UI code
> Change "Group" to "Policy" throughout the UI code

- src/components/FilePreview/FilePreview.svelte
- src/pages/policies/[policyId]/claims/[claimId].svelte
- remove the button and show file type to customer instead
- comment out code not being used yet
> remove delete button from FilePreview for now

- src/components/RoleAndPolicyMenu.svelte
- src/data/policies.ts
- src/helpers/routes.ts
- src/pages/admin/policies.svelte
- src/pages/customer/home.svelte
- src/pages/policies/[policyId].svelte
- src/pages/policies/[policyId]/claims.svelte
- src/pages/policies/[policyId]/claims/[claimId].svelte
- src/pages/policies/[policyId]/items/[itemId].svelte
- src/pages/policies/[policyId]/settings.svelte
- src/pages/policies/new.svelte
- Change "Corporate" to "Team" (re: policies) throughout the UI code
---
**NOTE:**
We will wait to merge this PR until the API is ready.
> Change "Corporate" to "Team" (re: policies) throughout the UI code

- src/components/AppHeader.svelte
- Show the user's name by their avatar/initial
> Show the user's name by their avatar/initial

- src/pages/policies/[policyId].svelte
> align-right more numbers in Datatable

- src/components/FileDropArea/FileDropArea.svelte
The button had top margin throwing off alignment
When flex items were scrunched up they had no margin
switch to flex row for mobile size screens
> Filedrop alignment and margin

- src/authn/user.ts
- src/components/App.svelte
- src/components/ItemsTable.svelte
- src/helpers/routes.ts
- src/pages/_layout.svelte
- src/pages/items.svelte
- src/pages/policies/[policyId]/home.svelte
- src/pages/policies/[policyId]/items.svelte
- Added home page with active items only
- Show active and inactive items on items page
- Admin is not affected by these changes
> add customer items page

- src/components/Checkout.svelte
- update the agree to terms verbiage.
> use "I have reviewed and agree to..."

- src/components/ClaimActions.svelte
- Signator and Steward have different "approve" actions at different states
> show approve or preapprove to appropriate admin type

- src/components/ItemDetails.svelte
- src/components/ItemsTable.svelte
* add the country location to the items list and item details components
* make the item details component a little more purty
> add policy item country

- src/components/CardsGrid.svelte
- This removes "Inactive" ItemCards from the Admin home page
> filter recent PolicyItem cards with isIncomplete

- src/components/ItemDetails.svelte
- src/components/ItemsTable.svelte
- src/components/forms/ItemForm.svelte
- src/pages/policies/[policyId].svelte
We are going with "Assigned To" instead of "Accountable Person"
> Accountable Person -> Assigned To

- src/components/ItemsTable.svelte
- src/data/items.ts
use the country value found on accountable_person by default
> add country to AccountablePerson

- src/pages/claims.svelte
- redirect Admins to ADMIN_HOME
> claims was not redirecting admins properly

- src/pages/home.svelte
> was not redirecting appRole: Admin to correct url

- src/data/policies.ts
- added a `limit` parameter  to `loadPolicies` and `searchPoliciesFor` and defaulted to '20'
> set default policies limit to 20, search to 50

- src/components/RoleAndPolicyMenu.svelte
- src/pages/_layout.svelte
- src/pages/settings.svelte
- It seems we don't the Policy Settings for Admin
> rename to Policy Settings and hide from Admin

- src/components/Checkout.svelte
- Checkout was showing ui for teams and household policies
> use account for teams on checkout and use entity code instead of name

- src/components/RoleAndPolicyMenu.svelte
- src/helpers/routes.ts
- src/pages/_layout.svelte
- src/pages/policies/[policyId].svelte
- add a link to policy details page for customers
- when switching role to Admin prevent viewing pages they should not be on
> show policy to customer

- src/components/SelectAccountablePerson.svelte
- src/components/forms/DependentForm.svelte
- src/components/forms/ItemForm.svelte
- src/components/index.ts
- src/components/mdc/Modal.svelte
- src/data/dependents.ts
- src/pages/policies/[policyId]/settings/dependents/[uuid].svelte
- src/pages/policies/[policyId]/settings/dependents/new.svelte
- src/validation/assertions.ts
* Add a SelectAccountablePerson component based on a Select component
* Add additional data validation to DependentForm around unique dependent names and dependent birth year
* Add ability to specify size of DependentForm (so it can be w-100 on the modal and w-50 elsewhere)
* Add a Modal component extending the Dialog.Alert component
* Additional features include the ability to programmatically close the modal, specify a title icon, and remove the default action buttons
* These changes could potentially be merged into ui-components once functionality is finalized
> add person item to accountable persons

- src/components/CountrySelector.svelte
- src/components/forms/DependentForm.svelte
- src/components/global.css
- src/components/index.ts
- src/pages/policies/[policyId]/settings.svelte
- src/pages/policies/new.svelte
- src/pages/settings/personal.svelte
- add SearchableSelect with countries list from api to DependentForm
> add CountrySelect and use in DependentForm and personal settings

- package-lock.json
- package.json
- src/pages/_layout.svelte
* Depends on https://github.com/silinternational/ui-components/pull/91/files
* Will complete once ui-components has been updated
> add urlPattern to drawer menu items

- src/components/global.css
- set all text to max of 80ch (this worked on text inputs too)
- del unused classes
> set all text to max-width of 80ch

- src/components/forms/ItemForm.svelte
- src/data/items.ts
Resolve an issue where policy item drafts could not be saved
> resolve coverage end date on policy item issue

- src/authn/user.ts
- src/components/App.svelte
- src/data/policies.ts
- src/pages/_layout.svelte
- src/pages/household.svelte
- src/pages/settings.svelte
- Tried to fix the `polices/null..` problem I was getting, but hard to replicate so not sure if its fixed
- fixed: loading policies was not happening at the right time so user was unable to add items unless they reloaded the page
> fixed loadPolicies bug & use getDefaulPolicyId

- src/business-rules/claim-payout-amount.ts
- src/components/ClaimActions.svelte
- src/pages/policies/[policyId]/claims/[claimId].svelte
> use upload instead of submit for receipt

- src/components/App.svelte
- src/components/global.css
- src/pages/terms.svelte
- Add real Terms of Service
- Set global line-height for paragraph tags to a better default
- Make "/terms" a public route
> Better line-height, and add real Terms of Service

- src/pages/privacy.svelte
> Add real Privacy Policy

- src/components/CardsGrid.svelte
- src/components/ItemsTable.svelte
- In the ItemsTable, indicate when coverage will end (if applicable)
- Don't show ItemCard for items whose coverage will end soon
> Fix display of items whose coverage will end soon

- README.md
- Document in the README where to go to find additional icons we can use
---
Because I keep forgetting.
> Document where to look for icons

- src/pages/terms.svelte
- Update Terms of Service to incorporate changes from Dec. 1, 2021
---
We don't yet need to notify users of this change since we have not yet gone live with the production version of this service.
> Update Terms of Service to incorporate changes from Dec. 1, 2021

- src/pages/policies/[policyId]/settings.svelte
When field is undefine show ''
> accountable person fields showing undefined

- src/components/MoneyInput.svelte
- I know the input `type="number"` but it causes a type error and this works fine
> fix some type errors in MoneyInput

- src/components/RadioOptions.svelte
the problem was that multiple radio options were given the same id
> allow radio options to be selected using label

- src/components/NoHouseholdIdModal.svelte
- added text and a link to create a team policy
> suggest a team policy if no household id

- src/pages/policies/[policyId]/claims/[claimId].svelte
> show claim resolution on claim details page

- src/pages/policies/[policyId]/claims/[claimId].svelte
- when changes are requested don't show "Upload.. " on button
- adjust message after submiting
> show "submit changes" when no file required

- src/components/ClaimCard.svelte
- src/components/banners/ClaimBanner.svelte
- src/data/states.ts
- src/pages/policies/[policyId]/claims.svelte
- src/pages/policies/[policyId]/home.svelte
- Admin shouldn't see this banner
> hide secondary claimCard banner from admin

- src/data/states.ts
- update title to "Awaiting review 3/3" https://trello.com/c/fCN5ZgVv/333-clarify-review-process
> change claimStates.Revew3.title

- src/pages/policies/[policyId].svelte
> sort policyItems so Inactive is not at the top

- src/pages/settings/personal.svelte
> email override not initializing properly on reload

- src/business-rules/claim-payout-amount.ts
- src/pages/policies/[policyId]/claims/[claimId].svelte
- use property supplied by api and delete ui logic
> use claim.total_payout

- src/components/AppFooter.svelte
> add footer links

- src/pages/_layout.svelte
- hide all other menu items and show only these
> show login, terms, and privacy for anonymous users

- src/components/CountrySelector.svelte
- src/components/RadioOptions.svelte
- src/components/SearchableSelect.svelte
- src/pages/policies/new.svelte
- src/pages/settings/personal.svelte
- country repopulates if none selected on:blur
- country now populates on hard refresh
> fix loading bug and empty country bug on blur

- src/business-rules/claim-payout-amount.ts
- src/components/forms/ClaimForm.svelte
- src/data/claims.ts
- search and destroy the nulls
> get rid of nulls in claimform except for one

- src/components/forms/ItemForm.svelte
- src/data/items.ts
> shortName to name

- src/pages/_layout.svelte
Perhaps a bit crude, but better than letting the user wander around broken links
> hide menu items while waiting for a policy to be created

- src/authn/user.ts
I searched for usage of this, and didn't find any.
> remove deprecated policy_id property on User

- src/components/forms/ItemForm.svelte
- for now we are allowing users to edit make and model after approval
- don't open MakeAndModelModal if the item is already approved
> if item is approved don't ask for make & model

- package-lock.json
- package.json
- src/components/AppDrawer.svelte
- src/components/AppFooter.svelte
- src/components/ClaimsTable.svelte
- center footer by adding right-margin equivalent to Drawer width when drawer is static(above mobile sizes)
- update ui-components to fix the Drawer/Page height issue to stop forcing the footer off the bottom of the page (pending release)
-
> Footer placement

- src/components/AppDrawer.svelte
> center and resize logo

- src/components/forms/ClaimForm.svelte
- src/data/claims.ts
- set claimForm radio button default
> repairableSelection default to 'repairable

- src/data/index.ts
- fix: users able to navigate around and view data in memory after logging out on another tab
> force login on 401

- src/components/forms/ClaimForm.svelte
- src/components/forms/ItemForm.svelte
- src/customTypes/@silintl/ui-components.d.ts
- src/pages/policies/[policyId]/claims/[claimId].svelte
> add minValue={'0'} to MoneyInputs and add missing props to type

- src/authn/index.ts
- src/authn/user.ts
- src/data/index.ts
- src/data/storage.ts
Storage code borrowed from silinternational/wecarry-ui
> fix circular dependency on authn/user

- src/components/Paginator.svelte
- src/components/index.ts
- src/data/policies.ts
- src/data/types/PaginatedData.ts
- src/helpers/routes.ts
- src/pages/admin/policies.svelte
this is the FE part to match the BE work I did today
> add paginator to policy list

- src/components/ClaimCard.svelte
- src/components/banners/ClaimBanner.svelte
- src/data/states.ts
- src/pages/policies/[policyId]/claims/[claimId].svelte
> show different claim states to Signator for Review

- package-lock.json
- package.json
- src/components/ItemsTable.svelte
- src/helpers/sort.ts
- src/pages/policies/[policyId].svelte
This PR will use <https://github.com/silinternational/ui-components/pull/108> to make the sort button appear on the left for numeric items.
> make ItemsTable sortable and use in policy view

- src/components/ClaimsTable.svelte
- src/components/ItemsTable.svelte
- src/helpers/sort.ts
- src/pages/policies/[policyId].svelte
- Add claim type to helpers/sort
- fix sorting paths and linking in ItemsTable
- make ClaimsTable sortable
> Make ClaimsTable sortable

- src/components/FilePreview/FilePreview.svelte
- src/data/claims.ts
- src/data/states.ts
- src/pages/policies/[policyId]/claims/[claimId].svelte
- claim file delete button and endpoint function
- Allow uploading a file on Revision status
- Show correct banners for Revision status
> Add claim file delete button and allow uploading file on Revision status

- src/components/ItemsTable.svelte
- src/components/RoleAndPolicyMenu.svelte
- src/components/mdc/_typography.scss
- menu items labels
- use text-transform on menu item text and subtitle
> change menu items labels and use text-transform

- src/data/claims.ts
- src/pages/admin/home.svelte
> filter out non actionable cards on admin/home

- src/components/App.svelte
- src/helpers/routes.ts
Fixed
- trying to reauthenticate on `/logout` and `/logged-out`
> fix logout redirecting to login

- src/authn/index.ts
- src/components/App.svelte
- src/components/AppDrawer.svelte
Check for public routes to show the app
Check if user logged in to hide the app
> add showApp store to hide app

- package-lock.json
- package.json
- src/data/claims.ts
- src/data/file.ts
- src/data/ledger.ts
- src/data/user.ts
- src/helpers/routes.ts
- src/helpers/sort.ts
- src/pages/_layout.svelte
- src/pages/admin/_components/LedgerList.svelte
- src/pages/admin/renewals.svelte
Performance is lacking when processing data on the scale of the production database, so work is yet to be done here.
> add policy renewals page for Steward

- src/components/FileLink.svelte
- src/components/index.ts
- src/data/ledger.ts
- src/helpers/dates.ts
- src/helpers/routes.ts
- src/pages/_layout.svelte
- src/pages/admin/_components/CreateReportModal.svelte
- src/pages/admin/reports.svelte
> create a new "ledger reports" page 

- .env.example
- src/components/AppDrawer.svelte
Cloudflare should set this env var to the branch it uses.
> added isNotProduction

- src/components/Breadcrumb.svelte
> removed capitalize and formatter did its thing

- src/components/FileLink.svelte
- src/data/index.ts
- src/data/ledger.ts
- src/helpers/routes.ts
- src/pages/admin/reports.svelte
- src/pages/admin/reports/[reportId].svelte
> create a new "ledger report detail" page with Reconcile capability

- src/components/forms/ClaimForm.svelte
- src/pages/policies/[policyId]/items/[itemId]/new-claim.svelte
> Add covered value to ClaimForm

- package-lock.json
- package.json
- src/components/TextFieldWithLabel.svelte
- src/components/forms/ItemForm.svelte
- src/customTypes/@silintl/ui-components.d.ts
- Update UI components
- rename TextFieldWithLabelAndDescription to TextFieldWithLabel and use built in `description` prop
> Update UI components

- src/components/ItemDetails.svelte
- src/helpers/dates.ts
- src/pages/admin/reports/[reportId].svelte
- show '-' instead of '1/1/1970'
- fix formatting for empty date
- fix type errors
with 1970-01-02
with 1970-01-01
> Do not show epoch dates

- src/components/AppDrawer.svelte
- src/components/Watermark.svelte
- Add Watermark.svelte
- replace text with Watermark
> Add Watermark component

- dist/index.html
- package-lock.json
- package.json
- src/components/CountrySelector.svelte
- src/components/CustomerReport.svelte
- src/components/FileLink.svelte
- src/components/Watermark.svelte
- import material icons as ui-components doesn't do this anymore
- use lang=ts instead of type=ts
- ui-components 5.0.1 fixes a MoneyInput error
> update ui-components and pull in material icons

- src/components/ClaimsTable.svelte
- payout column
- repair, replace and fmv cols until further feedback
> show payout amount in ClaimTable columns

- src/data/policies.ts
- src/pages/policies/[policyId]/settings.svelte
> add invites to policy settings

- src/components/InfoBoxModal.svelte
- src/components/ItemDetails.svelte
> location info box

- src/components/RadioOptions.svelte
- src/components/RemoveProfilePicModal.svelte
- src/components/index.ts
- src/data/user.ts
- src/pages/settings/personal.svelte
- Hide croppie after upload
- add remove button
- add modal
> Delete profile photo

- src/components/CreateCustomerReportModal.svelte
- src/components/CustomerReport.svelte
- src/data/ledger.ts
- src/pages/admin/reports/[reportId].svelte
- replace UI generated report with api generated report
- add reports table to show multiple report files
> Policy ledger reports

- src/components/FilePreview/FilePreview.svelte
- src/components/FilePreview/FilePreviews.svelte
- src/components/FilePreview/index.ts
- src/components/index.ts
- src/pages/policies/[policyId].svelte
- src/pages/policies/[policyId]/claims/[claimId].svelte
- src/pages/settings/personal.svelte
It seems I forked this branch off the previous one, so it might make more sense of it after merging the previous branch. Or the last [commit](https://github.com/silinternational/cover-ui/pull/475/commits/47477c9b84118263221a0eb39130b1a855492003) would be the changes after merging.
> add admin breadcrumbs to policy

- dist/index.html
- package.json
- rollup.config.js
> remove unused service-worker code

- src/business-rules/claim-payout-amount.ts
- src/components/forms/ClaimForm.svelte
- src/data/policies.ts
- src/data/types/claim-incident-types.ts
- src/data/types/policy-types-enum.ts
- src/data/user.ts
- moved PolicyType enum to own file
- move claim-incident-types to `/types`
> fix circular dependency

- src/components/AppHeader.svelte
- src/components/Datatable/ItemsTable.svelte
- src/components/RoleAndPolicyMenu.svelte
- src/components/global.css
- src/data/policies.ts
> truncate long policy names in menu and complete some todos

- src/components/RemoveDependentModal.svelte
- src/components/forms/DependentForm.svelte
- src/components/index.ts
- src/data/items.ts
- src/pages/policies/[policyId]/settings.svelte
> add RemoveDependentModal to `policy/settings' DependentForm

- src/components/Strikes.svelte
- src/pages/terms.svelte
- Add strikes and deductibles to terms
> add strikes and deductibles to terms

- src/components/Strikes.svelte
- replace "strikes" with "deductible adjustment"
> replace strike with deductible adjustment

- src/components/Datatable/ItemsTable.svelte
- added a function to copy `item.country` to `accountable_person.country` so sorting works
> no country on accountablePerson breaks sorting

- src/components/InfoModal.svelte
- src/components/forms/ClaimForm.svelte
- src/components/index.ts
- add info button next to MoneyInput
- add infoModal
> explain what fmv is with icon button and modal

- src/components/CustomerReport.svelte
- src/components/FileLink.svelte
- src/data/ledger.ts
- src/data/policies.ts
- src/pages/admin/reports.svelte
- src/pages/admin/reports/[reportId].svelte
- src/pages/policies/[policyId].svelte
- add on:expired to FileLink
- add ledgerReports store and UpdateLedgerReports
- get new report when url expires with on:expired
- get Policy Reports from Policy object
> Add ledgerReports store and renew report url

- src/pages/policies/[policyId]/claims/[claimId].svelte
> fix upload wrongly shown on ClaimStatus.Revision

- src/components/Datatable/ItemsTable.svelte
- src/components/index.ts
- src/data/items.ts
- src/pages/policies/[policyId].svelte
- added a filter and alternate button label for Approved Items
> add only approved items filter to table

- src/components/Checkout.svelte
> show min charge of 1 dollar on checkout

- src/components/forms/ItemForm.svelte
- src/components/global.css
- src/data/itemCategories.ts
- src/data/items.ts
> add an info Card to category selector in ItemForm

- src/components/RemoveDependentModal.svelte
- src/components/RemoveMemberModal.svelte
- src/components/forms/DependentForm.svelte
- src/components/forms/ItemForm.svelte
- src/components/global.css
- src/data/items.ts
- src/pages/policies/[policyId]/settings.svelte
- add option to reassign items when removing a policy member or dependent
> reassign items when deleting an accountable person

- package-lock.json
- package.json
- src/components/CreateCustomerReportModal.svelte
- src/components/banners/StatusBanner.svelte
- src/components/mdc/_typography.scss
- update ui-components and sass
- install tslib
> update to ui-components 6

- package-lock.json
- package.json
- src/components/mdc/Switch/Switch.svelte
- src/components/mdc/Switch/_index.scss
- src/components/mdc/Switch/index.js
- src/pages/policies/[policyId].svelte
- Added Switch
- simplified filtering of items
- used "hide inactive items" terminology for users
> Filter inactive items with Switch "hide" button

- src/pages/policies/[policyId].svelte
- Refactor the button label 
- add a control block to hide the button when viewing all items already.
> Hide view more items button when all items are shown

- src/components/AppDrawer.svelte
- src/components/CustomerReport.svelte
- src/components/Datatable/ItemsTable.svelte
- src/components/Datatable/types.ts
- src/components/RoleAndPolicyMenu.svelte
- src/components/global.css
- src/data/ledger.ts
- src/helpers/dates.ts
- src/helpers/money.ts
- src/helpers/routes.ts
- src/pages/policies/[policyId]/report.svelte
> monthly policy report for team and household

- src/pages/policies/[policyId]/claims.svelte
- add `{:else if $loading}` to show ...Loading claims
> fix: was showing "no claims" while loading claims

- src/components/AppFooter.svelte
- src/components/Banner.svelte
- src/components/ClaimCardBanner.svelte
- src/components/DateInput.svelte
- src/components/SearchableSelect.svelte
- src/components/Watermark.svelte
- src/components/banners/StatusBanner.svelte
- src/pages/policies/[policyId]/items/[itemId].svelte
- saw the style directive while looking up something else and thought it would be more readable
> refactor for readability using style directive

- dist/index.html
- To help our shared links on facebook, etc added open graph meta
> added open graph meta tagas

- src/components/index.ts
- src/data/entityCodes.ts
- src/helpers/routes.ts
- src/pages/_layout.svelte
- src/pages/admin/entities.svelte
- src/pages/admin/entities/[entityId].svelte
- src/pages/policies/[policyId]/settings.svelte
- src/pages/policies/new.svelte
- add /admin/entities
- add /admin/{entityId}
- in /policies/new and /policies/{policyId}/settings concatenate for the menu
- use new endpoints for EntityCodes
> Entity codes views

- src/pages/settings/personal.svelte
> remove unused code

- src/components/Datatable/CopyTableButton.svelte
- src/components/Datatable/ItemsTable.svelte
- src/components/Datatable/types.ts
- add CopyTableButton
- add serial number and button to show/hide it on ItemsTable
Added make and model
They are hidden by default
> Add copy button and serial number to ItemsTable 

- src/components/Datatable/CopyTableButton.svelte
> Remove unwanted elements

- src/components/Datatable/CopyTableButton.svelte
- Fix miss-aligned headers when copying ItemTable to clipboard
> Release 1.2.1

- src/components/BatchItemClone.svelte
- src/components/BatchItemDelete.svelte
- src/components/CustomerReport.svelte
- src/components/Datatable/CopyTableButton.svelte
- src/components/Datatable/ItemsTable.svelte
- src/components/InfoModal.svelte
- add info button to 'copy table contents' button
- add info button to 'create a report' button
- refactor InfoModal
- change a few var names
- use InfoModal in BatchItemDelete
> add info buttons and modals

- src/components/BatchItemClone.svelte
- src/components/BatchItemDelete.svelte
- src/components/CustomerReport.svelte
- src/components/Datatable/CopyTableButton.svelte
- src/components/Datatable/ItemsTable.svelte
- src/components/InfoModal.svelte
- https://github.com/silinternational/cover-ui/pull/543
> Release 1.3.0

- src/components/TextFieldWithLabel.svelte
- src/components/global.css
- src/data/entityCodes.ts
- src/pages/admin/_components/EntityModal.svelte
- src/pages/admin/entities.svelte
- src/pages/admin/entities/[entityId].svelte
> add EntityModal

- src/components/Datatable/ItemsTable.svelte
- src/pages/admin/_components/EntityModal.svelte
- replace svg with IconButton in ItemsTable
- fix spacing in entity form
> use icon button to improve accessibility

- src/components/banners/ItemBanner.svelte
- src/pages/admin/entities.svelte
- src/pages/admin/entities/[entityId].svelte
- src/pages/admin/home.svelte
- src/pages/admin/policies.svelte
- src/pages/admin/renewals.svelte
- src/pages/admin/reports.svelte
- src/pages/admin/reports/[reportId].svelte
> add Admin page titles

- src/components/AppDrawer.svelte
- src/pages/_layout.svelte
> hide the RoleAndPolicyMenu when anonymous

- src/components/AppDrawer.svelte
- use anchor and href instead of span and goto
> fix logo link

- src/components/AppDrawer.svelte
- src/pages/_layout.svelte
- src/pages/admin/home.svelte
- refresh recent activity on admin/home every 60 seconds
> poll on admin home

- src/components/AppDrawer.svelte
- increase margin on nav menu
see https://trello.com/c/94zThKGp/542-easy-css-show-policy-spacing
> increase margin on nav menu

- package-lock.json
- package.json
- src/components/AppHeader.svelte
- src/components/global.css
- src/pages/policies/[policyId]/items/[itemId].svelte
- TextArea text overlapping with counter
- fixed height restriction
> fix message text area

- src/components/BatchItemDelete.svelte
- src/components/CustomerReport.svelte
- src/components/Datatable/CopyTableButton.svelte
- src/components/InfoModal.svelte
- src/components/forms/ClaimForm.svelte
- the modal needed the internal button in some but not all location
> fix info modal for claim form

- src/helpers/money.ts
- show '$0.00' for premium instead of ''
> show '$0.00' for premium instead of ''

- src/components/Checkout.svelte
- src/components/Description.svelte
- src/components/ItemDetails.svelte
- src/components/global.css
- use css to preserve whitespace in Descriptions
- fix some ts warnings/errors
> preserve whitespace in description

- dist/index.html
- src/components/mdc/_typography.scss
- fix font not loading correctly
The 2 on the right are loaded correctly while the left browser (staging) is not
> fix font loading

- src/components/Datatable/ItemsTable.svelte
- remove /view from "Draft" item menu as it directs to /edit
> remove view from menu for draft items

- src/components/ItemDetails.svelte
- show the next renew date if there is no end date on an item
> add renew date

- src/components/Datatable/ItemsTable.svelte
- src/components/RoleAndPolicyMenu.svelte
- src/components/mdc/_typography.scss
- remove capitalize from List Items
- The desire is to have title case but as there is no text-transform property that is suitable, we need do it in the strings themselves
note `ItemCategoriesList` only capitalized the first word
> override capitalize on list items

- src/components/RadioOptions.svelte
- src/components/forms/ClaimForm.svelte
- src/data/items.ts
- src/pages/policies/[policyId]/settings.svelte
- Remove todos that seem irrelevant or completed
- add a bit more margin to radio options
> Remove some todos

- src/components/RoleAndPolicyMenu.svelte
- src/data/claims.ts
- complete TODO: show household policy name in menu
> show household policy name in menu

- src/components/ItemDetails.svelte
- startDate is not the current year on old items
> Fix renew date

- rollup.config.js
> cleanup rollup html template configuration

- src/business-rules/claim-payout-amount.ts
- src/components/forms/ClaimForm.svelte
- src/components/forms/claims/claimFormHelpers.ts
- src/components/forms/claims/types.ts
- src/data/claims.ts
- src/helpers/money.ts
- An initial attempt to try to clean up ClaimForm
- fix a bug where the wrong payoutOption is submitted due to a reactive statement not firing off as expected
- fix some typescript errors/warnings
> Refactor claim form

- src/components/forms/ClaimForm.svelte
- src/components/forms/claims/_components/LossReasonRadioOptions.svelte
- src/components/forms/claims/_components/PayoutRadioOptions.svelte
- src/components/forms/claims/_components/RepairableRadioOptions.svelte
- src/components/forms/claims/_components/index.ts
- src/pages/admin/reports.svelte
- factor out some components from ClaimForm
- refactor a reactive statement
- remove unused import
> refactor ClaimForm

- src/components/forms/ClaimForm.svelte
- src/components/forms/claims/_components/ItemSelector.svelte
- src/components/forms/claims/_components/index.ts
- src/pages/policies/[policyId]/claims/new.svelte
- move ItemSelector into ClaimForm
> Add item selector

- src/components/DateInput.svelte
- src/components/RadioOptions.svelte
- src/components/forms/ClaimForm.svelte
- src/components/forms/claims/_components/LossReasonRadioOptions.svelte
- src/components/forms/claims/_components/PayoutRadioOptions.svelte
- src/components/forms/claims/_components/RepairableRadioOptions.svelte
- src/components/forms/claims/claimFormHelpers.ts
- instead of disabling buttons use validation and required on inputs
> improve claim form validation

- src/components/forms/ClaimForm.svelte
- src/components/forms/claims/claimFormHelpers.ts
- move situationDescription validation to validateForDraft
> validate situationDescription for Draft

- src/components/forms/SearchForm.svelte
> Replace ugly search field label using component properties

- src/components/AppDrawer.svelte
- src/components/BatchItemClone.svelte
- src/components/BatchItemDelete.svelte
- src/components/CustomerReport.svelte
- src/components/Datatable/CopyTableButton.svelte
- src/components/Datatable/ItemsTable.svelte
- src/components/Strikes.svelte
- src/components/Watermark.svelte
- src/components/global.css
- src/pages/policies/[policyId].svelte
[CVR-613](https://itse.youtrack.cloud/issue/CVR-613) Download UX for Sage and NetSuite
[CVR-629](https://itse.youtrack.cloud/issue/CVR-629) Policy page: Semantic headings
[CVR-630](https://itse.youtrack.cloud/issue/CVR-630) Download UI for Sage and NetSuite
[CVR-633](https://itse.youtrack.cloud/issue/CVR-633) Fix: watermark interferes with mouse clicks
[CVR-628](https://itse.youtrack.cloud/issue/CVR-628) Fix "Show S/N" vertical placement
This pull will result in good-looking but non-functional Download buttons on the Policy page.
> Feature/download non-functioning

- package-lock.json
- package.json
- src/components/Datatable/PolicyItems/ItemsTable.svelte
- src/components/Datatable/PolicyItems/itemTableHelpers.ts
- src/data/itemCategories.ts
[CVR-644](https://itse.youtrack.cloud/issue/CVR-644/ItemTable-Prepend-item-names-with-category-icon)
- Add icon to ItemsTable
- Add "iconify-icon"
- Add itemCategoryName
> CVR-644 add icon to itemsTable

- src/pages/policies/[policyId].svelte
[CVR-683](https://itse.youtrack.cloud/issue/CVR-683) Remove premium rate from Policy page
> CVR-683 Remove premium rate from Policy page

- rollup.config.js
- src/components/mdc/_typography.scss
[CVR-674](https://itse.youtrack.cloud/issue/CVR-674/Improve-Button-typography)
- typography
- Button letter spacing
> change button typography letter spacing CVR-674

- src/components/ItemDetails.svelte
[Make the ItemDetails background consistent across views](https://github.com/silinternational/cover-ui/commit/e63366ebb3cef2aeafd6a199e125e1c5ae4483f8)
Prep for 
-  [CVR-681](https://itse.youtrack.cloud/issue/CVR-681) Item Checkout page for category-based premium %
- [CVR-682](https://itse.youtrack.cloud/issue/CVR-682) Item Details page for category-based premium %
> Make the ItemDetails background consistent across views

- src/components/Datatable/PolicyItems/ItemsTable.svelte
- src/components/Datatable/PolicyItems/itemTableHelpers.ts
- src/data/itemCategories.ts
- Use item_categories.key to determine which category icon to show
> CVR-699 Base category icon on "keys" field

- src/authn/token.ts
[CVR-47](https://itse.youtrack.cloud/issue/CVR-47/Store-authentication-seed-etc.-in-session-storage-not-localStorage-so-that-closing-the-browser-clears-it)
- use sessionStorage not localStorage
> use sessionStorage CVR-47

- src/components/ItemDetails.svelte
- src/data/itemCategories.ts
- src/pages/policies/[policyId]/claims/[claimId].svelte
- src/pages/terms.svelte
Issue [CVR-707](https://itse.youtrack.cloud/issue/CVR-707/new-claim-deductible-UI)
---
- Show minimum deductible (when applicable) for replacements
- Mention the possible minimum deductible in Terms of Use
- Show minimum deductible during checkout, when applicable
> CVR-707 Show claim deductible, where applicable

- src/components/AccountablePeopleList.svelte
- src/pages/admin/_components/EntityModal.svelte
- src/pages/admin/entities/[entityId].svelte
- src/pages/policies/[policyId]/settings.svelte
- src/pages/policies/new.svelte
- Addresses some suggestions made in https://github.com/silinternational/cover-ui/pull/634
> change some fields and labels

- package-lock.json
- Trying to resolve a number of dependabot alerts
> ran npm update

- package-lock.json
- package.json
- update a few Prettier related deps
- While starting to create an issue for tailwindcss because of multiple dependabot warnings I noticed we had tailwind installed so I installed the correct tailwindcss instead.
- I guess this means none of the utility classes were being applied yet, but I don't think there were many.
- we should verity tailwind css is working
> tailwind is not tailwindcss

- Makefile
- src/components/FilePreview/FilePreview.svelte
- src/components/ItemDetails.svelte
- src/components/Paginator.svelte
- src/components/RoleAndPolicyMenu.svelte
- src/components/SelectAccountablePerson.svelte
- src/components/YearInput.svelte
- src/components/banners/ClaimBanner.svelte
- src/components/forms/ClaimForm.svelte
- src/components/forms/DependentForm.svelte
- src/components/forms/ItemForm.svelte
- src/data/items.ts
- src/pages/admin/home.svelte
- src/pages/policies/[policyId].svelte
- src/pages/policies/[policyId]/claims/[claimId].svelte
- src/pages/policies/[policyId]/items/new.svelte
- src/pages/policies/[policyId]/settings.svelte
- start and end date from ItemForm
- make check
- make lint
- broken import
- lots of ts errors/warning (down to 5 mostly from bad routify types)
> remove start and end date from item and fix ts errors

- src/components/RecentActivityTable.svelte
[CVR-743](https://itse.youtrack.cloud/issue/CVR-743/monthly-annual-premiums-in-RecentActivityTable)
> CVR-743 add monthly amount to recent activity table

- src/pages/admin/_components/AuditsOrRepairTable.svelte
[CVR-744](https://itse.youtrack.cloud/issue/CVR-744/add-monthly-to-AuditOrRepairTable)
> CVR-744  ad monthly to audit or repair table

- src/components/ItemDetails.svelte
- Only show the minimum deductible if it is greater than 1 cent
> CVR-727: Only show the minimum deductible if it is greater than 1 cent

- src/components/RecentActivityTable.svelte
[CVR-743](https://itse.youtrack.cloud/issue/CVR-743/monthly-annual-premiums-in-RecentActivityTable)
- I missed adding this to the recent claims table
> CVR-743  add monthly premium to recent claim section

- rollup.config.js
- src/components/mdc/_typography.scss
[CVR-674](https://itse.youtrack.cloud/issue/CVR-674/Improve-Button-typography)
- typography
- Button letter spacing
These were reverted accidentally
> change button spacing and typography

- src/pages/policies/[policyId]/claims/[claimId].svelte
[CVR-710](https://itse.youtrack.cloud/issue/CVR-710) Approval button says "Okay To Replace" when it should say "Okay To Repair"
---
- Fix logic bug re: needs receipt vs. repair/replacement
> CVR-710: Fix logic bug re: needs receipt vs. repair/replacement

- src/data/ledger.ts
- src/pages/admin/renewals.svelte
- Add "Monthly Renewal" section/buttons to `/admin/renewals` page
> CVR-752: Add monthly renewals button

- src/components/ItemDetails.svelte
- src/pages/policies/[policyId]/items/[itemId]/checkout.svelte
[CVR-748](https://itse.youtrack.cloud/issue/CVR-748/After-discarding-item-during-checkout-go-back-to...-somewhere)
> fix bug preventing goto after removing item in checkout CVR-748

- src/components/RemoveDependentModal.svelte
- src/components/RemoveMemberModal.svelte
- src/components/forms/DependentForm.svelte
- src/data/items.ts
- src/pages/policies/[policyId]/settings.svelte
[CVR-106](https://itse.youtrack.cloud/issue/CVR-106/Error-when-trying-to-delete-dependent-who-is-an-accountable-person-on-an-Item-with-no-coverage.)
- dependent/members delete error due to not updating the item first
> fix deleting a dependent while reassigning items CVR-106

- package-lock.json
- package.json
- Use fixed version of `Select` component, to ensure selections "stick"
Documentation for the two release is here:
https://github.com/silinternational/ui-components/releases
> Use fixed version of `Select` component, to ensure selections "stick"

- package-lock.json
- package.json
- remove sass. I realized sass code is being parsed by plugins and nothing uses sass.
> Uninstall sass

- src/components/App.svelte
- src/components/AppDrawer.svelte
- src/components/AppHeader.svelte
- src/pages/_layout.svelte
- fix/silence [routify docs](https://www.routify.dev/docs/helpers#before-url-change) or types don't show { url } in beforeUrlChange
- silence a ts error from routify
- fix afterPageLoad type
> fix wrong routify types

- package-lock.json
- package.json
- rollup.config.js
- src/components/AppFooter.svelte
[CVR-784](https://itse.youtrack.cloud/issue/CVR-784/clean-up-build-warnings)
- move remaining warnings to a filter list with a Todo
- update svelte-preprocess to remove a warning
see https://github.com/rollup/rollup/issues/408 for more info on filtering warnings
> CVR-784  Move build warnings to a list

- src/pages/policies/[policyId]/items.svelte
[CVR-800](https://itse.youtrack.cloud/issue/CVR-800/Cover-Tech-Request-The-hide-inactive-checkbox-is-missing-on-the-item-list-view)
> CVR-800  add hide inactive to items view

- src/pages/policies/[policyId]/items/[itemId].svelte
> on item view add a button to go back to items

- src/data/ledger.ts
- src/pages/admin/renewals.svelte
[CVR-772](https://itse.youtrack.cloud/issue/CVR-772)
> use safe_to_process CVR-772

- src/pages/policies/[policyId].svelte
- src/pages/policies/[policyId]/settings.svelte
- src/pages/policies/new.svelte
- "Account Detail" -> "Ledger Entry Description"
- field widths too small
[CVR-775](https://itse.youtrack.cloud/issue/CVR-775)
> text consistency and fix some field widths CVR-775

- src/helpers/dates.ts
- src/pages/policies/[policyId]/claims/new.svelte
[CVR-808](https://itse.youtrack.cloud/issue/CVR-808)
> prevent claim against non-active item CVR-808

- package-lock.json
- package.json
- src/components/MakeAndModelModal.svelte
- src/components/SelectAccountablePerson.svelte
- src/components/YearInput.svelte
- src/components/forms/ItemForm.svelte
[CVR-93](https://itse.youtrack.cloud/issue/CVR-93)
TODO: update ui-components to released version when available
> Fix ItemForm CVR-93

- package-lock.json
- package.json
- src/components/RadioOptions.svelte
- src/components/forms/ClaimForm.svelte
- src/components/forms/claims/_components/LossReasonRadioOptions.svelte
- src/components/forms/claims/_components/PayoutRadioOptions.svelte
Make required fields red when submitting empty
[CVR-93](https://itse.youtrack.cloud/issue/CVR-93)
> fix claim form validation CVR-93

- src/components/Description.svelte
- src/components/forms/ClaimForm.svelte
Fix forms inconsistent use of labels
Before:
After
> fix claim form labels

- src/components/CountrySelector.svelte
- src/components/forms/DependentForm.svelte
- src/components/mdc/_theme.scss
[CVR-93](https://itse.youtrack.cloud/issue/CVR-93)
> fix dependent validation CVR-93

- src/components/CountrySelector.svelte
- src/components/forms/DependentForm.svelte
- src/components/mdc/_theme.scss
- src/pages/policies/new.svelte
[CVR-93](https://itse.youtrack.cloud/issue/CVR-93)
> new policy validation show errors CVR-93

- src/authn/index.ts
- src/components/RoleAndPolicyMenu.svelte
- src/data/index.ts
- src/pages/_layout.svelte
- src/pages/index.svelte
- redirect to return-to param
[CVR-774](https://itse.youtrack.cloud/issue/CVR-774)
--
> add return to param CVR-774

- src/data/items.ts
- fix offering to update items with Inactive or Denied CoverageStatus when deleting dependents or members which will fail
> only update mutable items

- src/components/Datatable/PolicyItems/BatchItemDelete.svelte
- src/components/Datatable/PolicyItems/ItemsTable.svelte
- use item assertions when deleting items
[CVR-816](https://itse.youtrack.cloud/issue/CVR-816)
> use item assertions when deleting items CVR-816

- src/pages/invite/[uuid].svelte
- message for ErrorInviteExpired error
> show invite expired message
